### ISSUE TITLE
Auto add entities based on wild card search (or device-class) and add filer option to exclude some of them

### ISSUE THREAD

**Issue by Tom-ahawk** [maxwroc/battery-state-card#1]
Finally, a battery card!

Any change your card can get a wild card for entities and attributes?
And an exclude value option (some sensors like FIbaro can also be wired, the battery value is then defaulted to 4)

Cheers.

My cuurent setup:

```
card:
  show_header_toggle: false
  title: Sensor Battery Status
  type: entities
filter:
  exclude:
    - state: '4'
  include:
    - entity_id: sensor.fib_*_battery_level
      options:
        style: |
          :host {
          --paper-item-icon-color: 
           {% if states(config.entity)|float <= 20 %} 
             red
           {% elif states(config.entity)|float <= 35 %}
             orange
           {% else %}
             var( ---state-icon-color )
           {% endif %}
           ;
           }
sort:
  method: state
  numeric: true
  reverse: false
type: 'custom:auto-entities'
```

**Comment by maxwroc** [comment]
Interesing idea with the wildcard entity search! I'm slightly concerned it can be a bit slow if you have a lot of entities in your HA. 

HA updates the cards "every time" (probably it is throttled) when any antity state changes (even if it's not used in the card). So in this case I would need to iterate over the entire collection of entities and get their state. But since you're saying that you have almost similar setup for the other card I will give it a try. 

If it is ok perfwise I will add it in similar way as you have it in your example. If not I could do some kind of discovery mode in which list of found entities will be printed on the card - you would be able to copy it over to the configuration.

I don't see any problems with state filtering so I will add it for sure

**Comment by mdegat01** [comment]
FYI @Tom-ahawk this card works with auto-entities.  I'm using it right now like this:
```yaml
- card:
    show_header_toggle: false
    title: Battery levels
    type: 'custom:battery-state-card'
    color_gradient:
      - '#ff0000'
      - '#ffff00'
      - '#00ff00'
  filter:
    exclude:
      - entity_id: '*_phone_*'
      - state: Ok
    include:
      - entity_id: sensor.*_battery_level
      - entity_id: sensor.*_battery_health
  show_empty: false
  sort:
    method: state
    numeric: true
  type: 'custom:auto-entities'
```
So @maxwroc its up to you if you want to implement this yourself in your card or simply point people to [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) as a solution to this problem.

**Comment by Tom-ahawk** [comment]
It works fine with the 'custom:auto-entities' card.

**Comment by maxwroc** [comment]
Reopening this as there is more and more asks for the same

**Comment by jwelter1971** [comment]
As an FYI the sort/collapse option also works wrapped in auto-entities:

   ```
  - type: custom:auto-entities
        card:
          type: custom:battery-state-card
          title: "Battery Levels"
          secondary_info: last_updated
          sort_by_level: "asc"
          collapse: 4
        filter:
          include:
            - entity_id: sensor.*_battery_level
            - entity_id: sensor.*_battery

```

**Comment by maxwroc** [comment]
Yes all of the card-level options will be working

**Comment by maxwroc** [comment]
For others looking for similar solution: please check the filters functionality which was added in v1.3.0.

# You don't need to use auto-entities any more!

Check the documentation https://github.com/maxwroc/battery-state-card#filter-groups 

Example use:
https://github.com/maxwroc/battery-state-card#entity-filtering-and-bulk-renaming
```yaml
- type: 'custom:battery-state-card'
  title: Filters
  sort_by_level: "asc"
  bulk_rename:
    - from: "Battery Level" # simple string replace (note: "to" is not required if you want to remove string)
      to: "sensor"
    - from: "/\\s(temperature|temp)\\s/" # regular expression
      to: " temp. "
  entities:
    # entities requiring additional properties can be added explicitly
    - entity: sensor.temp_outside_battery_numeric
      multiplier: 10
      name: "Outside temp. sensor"
  filter:
    include: # filters for auto-adding
      - name: entity_id # entities which id ends with "_battery_level"
        value: "*_battery_level"
      - name: attributes.device_class # and entities which device_class attribute equals "battery"
        value: battery
    exclude: # filters for removing
      - name: state # exclude entities above 99% of battery level
        value: 99
        operator: ">"
```
