### ISSUE TITLE
Default filter operator ("exists") doesn't work

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#108]
**Describe the bug**
When there is no `value` and `operator` property in the filter definition it should fallback to "exists" operator and all entities having particular property/attribute defined in `name` prop should be matched

**YAML configuration**
```yaml

      - type: 'custom:battery-state-card'
        title: Filters
        sort_by_level: "asc"
        bulk_rename:
          - from: "Battery Level" # simple string replace (note: "to" is not required if you want to remove string)
            to: "sensor"
          - from: "/\\s(temperature|temp)\\s/" # regular expression
            to: " temp. "
        entities:
          # entities requiring additional properties can be added explicitly
        -   entity: sensor.temp_outside_battery_numeric
            multiplier: 10
            name: "Outside temp. sensor"
        filter:
          include: # filters for auto-adding
            - name: entity_id # entities which id ends with "_battery_level"
              value: "*_battery_level"
            - name: attributes.device_class # and entities which device_class attribute equals "battery"
              value: battery
            - name: attributes.battery_level 
              # you don't specify the value so all entities with battery_level attrib will be included

```

**Screenshots**

**Version**

v1.4.0
