### ISSUE TITLE
  Component error: resources - Integration 'resources' not found.

### ISSUE THREAD

**Issue by Hoekeren** [maxwroc/battery-state-card#110]
**Describe what is wrong**
I have installed the card with HACS and restarted HA. 
Thereafter I have added :

resources:
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module
 
to my configuration.yaml.

When performing a configuration check before restart, I am prompted with;

  Component error: resources - Integration 'resources' not found.
**YAML configuration**
```yaml


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  
resources:
  - url: /hacsfiles/battery-state-card/battery-state-card.js
    type: module
  
  
# Text to speech
tts:
  - platform: google_translate
    language: 'da'

### Inklution af seperate yaml    
# switch: !include switch.yaml
#timer: !include timer.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
light: !include lights.yaml
recorder: !include recorder.yaml
#resources: !include resources.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml


# Z-Wave
zwave:
  usb_path: /dev/ttyACM1
  device_config: !include zwave_device_config.yaml
  
# Sonoff
sonoff:
  username: !secret sonoff_user 
  password: !secret sonoff_pass 
  reload: always
  
# ZHA-map
zha_map:

```

**Screenshot**

**Version**
Card 1.5.2
Homeassistant 0.113.3
Host RPI4B+
