### ISSUE TITLE
? in battery icon when 100%

### ISSUE THREAD

**Issue by brinzlee** [maxwroc/battery-state-card#111]
**Describe the bug**
I have many battery status entities set up on one page. But most of the time the battery state icon for those that are at 100% will be green with a ? mark inside it. If I refresh the page the icon goes solid green and the ? disappears for a while then returns. I have deleted the Battery State Card a few times in case is was installed incorrectly but I can't work out why it does this. All the other icons that are less than 100% in battery level always show up correctly

**How to reproduce**
As above

**Expected behavior**

**YAML configuration**
```yaml
`color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: sensor.aeotec_dsb45_water_sensor_battery_level
    name: Garage Aeotec DSB45 Flood Sensor
  - entity: sensor.fibaro_system_fgfs101_zwave_flood_sensor_battery_level
    name: Kitchen FIBARO FGFS101 Flood Sensor
  - entity: sensor.fibaro_system_fgk101_door_opening_sensor_battery_level
    name: Loft Bedroom Window Sensor
  - entity: sensor.fibaro_system_fgk10x_door_opening_sensor_battery_level
    name: Loft Bathroom Window Sensor
  - entity: sensor.fibaro_system_fgms001_zw5_motion_sensor_battery_level
    name: Kitchen Motion Sensor
  - entity: sensor.lumi_remote_b1acn01_32_battery_level
    name: Lounge Smart Switch
  - entity: sensor.mi_magic_cube_battery_level
    name: Magic Cube Sensor
  - entity: sensor.motion_sensor_battery_level
    name: Motion Sensor
  - entity: sensor.multi_sensor_conservatory_battery_level
    name: Conservatory Multi Sensor
  - entity: sensor.multi_sensor_lounge_battery_level
    name: Lounge Multi Sensor
  - entity: sensor.multi_sensor_master_bedroom_battery_level
    name: Master Bedroom Multi Sensor
  - entity: sensor.multi_sensor_olivias_bedroom_battery_level
    name: Olivias Bedroom Multi Sensor
  - entity: sensor.smart_switch_battery_level_2
    name: Master Bedroom Switch
  - entity: sensor.smart_switch_2_battery_level
    name: Olivias Bedroom Switch
  - entity: sensor.vibration_23_battery_level
    name: Vibration Sensor A
  - entity: sensor.vibration_sensor_battery_level
    name: Vibration Sensor B
  - entity: sensor.water_sensor_main_bathroom_battery_level
    name: Main Bathroom Flood
  - entity: sensor.water_sensor_master_bath_suite_battery_level
    name: Master Bathroom Flood
title: Sensor Battery Level Status
type: 'custom:battery-state-card'
`


```

**Screenshots**

**Version**
< 1.4.1>
