### ISSUE TITLE
[1.5.0] i.setConfig is not a function

### ISSUE THREAD

**Issue by syphernl** [maxwroc/battery-state-card#141]
**Describe the bug**

After updating to v1.5.0 my Battery State Card is broken and show an error in the frontend.

**How to reproduce**

Update from 1.4.2 to 1.5.0.

**Expected behavior**

No error.

**YAML configuration**
```yaml
type: 'custom:auto-entities'
show_empty: false
card:
  type: 'custom:battery-state-card'
  title: Battery Devices
  sort_by_level: asc
  collapse: 5
  bulk_rename:
    - from: '_battery_level'
      to: ''
    - from: '_battery'
      to: ''
filter:
  include:
    - domain: sensor
      entity_id: '*_battery'
    - domain: sensor
      entity_id: '*_battery_level'
    - device_class: battery
  exclude:
    - domain: automation
    - domain: script
    - domain: alert
    - domain: persistent_notification

```

**Screenshots**

**Version**

* Problematic version: v1.5.0. 
* Last good version: v1.4.2. 

Both on HA 0.116.0
