### ISSUE TITLE
charging state values as a list

### ISSUE THREAD

**Issue by gitmayer** [maxwroc/battery-state-card#144]
I'm having trouble using values of the charging state in a list. Previously using true for my value of charging state works, but I want it to say its charging if the value is not zero.  More specifically, if the value is 1 thru 4.

Per the documenation state can take a list of any type. "state | list(any) |   | v1.1.0 | List of values indicating charging in progress -- | -- | -- | -- | --"

Below is my YAML for the card, I have updated to the newest version only to still have this issue.

```
color_thresholds:
  - color: '#fb0000'
    value: 20
  - color: '#fb8b00'
    value: 40
  - color: '#f9fb00'
    value: 60
  - color: '#7abb00'
    value: 80
  - color: '#3bab00'
    value: 100
entities:
  - charging_state:
      attribute:
        name: is_charging
        value:
          - 1
          - 2
          - 3
          - 4
    entity: sensor.jon_battery
  - charging_state:
      attribute:
        name: is_charging
        value: true
    entity: sensor.melissa_battery
  - sensor.front_door_battery
secondary_info: last_updated
tap_action:
  action: more-info
type: 'custom:battery-state-card'

```
