### ISSUE TITLE
more-info tap action is broken

### ISSUE THREAD

**Issue by Hypfer** [maxwroc/battery-state-card#149]
**Describe the bug**

The more-info tap action is broken

**How to reproduce**

- Define card with single entity
- Set tap action to more-info
- Tap/Click

**Expected behavior**

More-info opens

**YAML configuration**
```yaml
type: 'custom:battery-state-card'
tap_action: more-info
entities:
  - sensor.keychain_beacon_battery

```

**Screenshots**

**Version**

Card Version v1.5.0
Home Assistant 0.116.2

I'm pretty sure that this is caused by this:
https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/
