### ISSUE TITLE
Filter wildcard fail

### ISSUE THREAD

**Issue by ARNik** [maxwroc/battery-state-card#151]
All my battery sensors have "_battery" endings.

So I created a filter:

```
filter:
  include: # filters for auto-adding
    - name: entity_id # entities which id ends with "_battery"
      value: "*_battery"
```

But the filter also adds all entities that have **entiti_id** like **"_battery_health"** and **"_battery_state"**:

![Снимок экрана 2020-10-26 224328](https://user-images.githubusercontent.com/3407744/97220559-b6ad8080-17dc-11eb-96db-9b4c5cda3f76.png)
