### ISSUE TITLE
Changing Thresholds for Gradients

### ISSUE THREAD

**Issue by bjs-pdx** [maxwroc/battery-state-card#156]
I'd like to change the thresholds being used for the gradient option.  Tried just adding color and threshold settings to file but that didn't work.  I'd like to set thresholds at 75, 85 and 100 since the sensors I'm monitoring go critical at 60%.

**YAML configuration**  N/A
```yaml

# paste your card configuration here
type: 'custom:battery-state-card'
title: Color gradient
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - binary_sensor.barn1
  - binary_sensor.barn2
  - binary_sensor.barn3
  - binary_sensor.barn_motion_1
  - binary_sensor.barn_motion_2
  - binary_sensor.kitchen_door
  - binary_sensor.deck_door
  - binary_sensor.front_door
  - binary_sensor.closet_door
  - binary_sensor.vineyard_door
  - binary_sensor.closet
  - binary_sensor.house_motion_1


```

**Screenshot**

**Version**
