### ISSUE TITLE
Custom icon doesn't show up

### ISSUE THREAD

**Issue by azrael783** [maxwroc/battery-state-card#162]
**Describe the bug**
I tried to use the new feature and wanted to set a different icon. But it doesn't work.

**How to reproduce**

**Expected behavior**
The icon should change

**YAML configuration**
```yaml
type: entities
entities:
  - entity: sensor.canon_tr8500_series
  - entity: input_number.tinte_schwarz_gross
    icon: 'mdi:water'
    type: 'custom:battery-state-card'
  - entity: input_number.tinte_schwarz
    type: 'custom:battery-state-card'
  - entity: input_number.tinte_cyan
    type: 'custom:battery-state-card'
  - entity: input_number.tinte_gelb
    type: 'custom:battery-state-card'
  - entity: input_number.tinte_magenta
    type: 'custom:battery-state-card'
title: Drucker Status
show_header_toggle: false
```

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44697375/98449453-13d9f800-2134-11eb-9ec6-ae3cde03a926.png)

**Version**
Card version 1.6.0
HA version 0.116.4
