### ISSUE TITLE
Support regex on bulk_rename setting

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#164]
**Is your feature request related to a problem? Please describe.**

Need to create couple of rules to cover similar cases.

**Describe the solution you'd like**

Support regex value in `from` field in the similar way how it is done in filters

**Additional context**

**Comment by tmchow** [comment]
Would love to get this working. I'm stuck right now because this regex will not work to do text deletions. 

```

type: 'custom:battery-state-card'
title: Nest Protects
sort_by_level: asc
tap_action: more-info
state_map:
  - from: Ok
    to: 100
  - from: Replace
    to: 25
bulk_rename:
  - from: /(battery health)/i
    to: ''
filter:
  include:
    - name: entity_id
      value: '*_nest_protect_battery_health'
```
