### ISSUE TITLE
secondary_info not appearing

### ISSUE THREAD

**Issue by ktownsend-personal** [maxwroc/battery-state-card#165]
**Describe what is wrong**
The `secondary_info` is not appearing. Am I doing it wrong, or is this not possible?

**YAML configuration**
```yaml
type: 'custom:battery-state-card'
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
filter:
  exclude:
    - name: entity_id
      value: '*iphone*'
  include:
    - name: entity_id
      value: sensor.*battery_level
secondary_info: last_updated
sort_by_level: asc
tap_action:
  action: more-info
```

**Screenshot**
![image](https://user-images.githubusercontent.com/22361432/98718938-b375d100-2354-11eb-8b06-a9211452baa2.png)

**Version**
card version 1.6.1
