### ISSUE TITLE
Be able to use color_gradient and color_thresholds concurrently

### ISSUE THREAD

**Issue by danielbrunt57** [maxwroc/battery-state-card#166]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I've discovered that color_gradient takes precedence and overrides color_thresholds.  It would be nice to control the color gradient points via color_thresholds

**For Example**
```
bulk_rename:
  - from: ': Battery Level'
  - from: Battery Level
  - from: Battery
collapse: 5
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
color_thresholds:
  - value: 70
    color: red
  - value: 90
    color: yellow
  - value: 100
    color: green
entities:
  - entity: sensor.vog_l04_battery_level
    charging_state:
      entity_id: sensor.vog_l04_battery_state
      state: charging
      icon: 'mdi:flash'
      color: yellow
  - entity: sensor.zm1701_electronic_deadbolt_door_lock_battery_level
filter:
  include:
    - name: entity_id
      value: '*_battery_level'
secondary_info: last_updated
sort_by_level: asc
type: 'custom:battery-state-card'
```
