### ISSUE TITLE
Icon override

### ISSUE THREAD

**Issue by BananaLoaf** [maxwroc/battery-state-card#168]
**Describe the bug**
Color gets overriden, but the icon does not

**Expected behavior**
_mdi:wifi-strength-4_ should change to _mdi:wifi-strength-off_

**YAML configuration**
```yaml
  - type: 'custom:battery-state-card'
    entities:
      - entity: sensor.wifi_connection
        icon: 'mdi:wifi-strength-4'
        charging_state:
          state: <not connected>
          icon: 'mdi:wifi-strength-off'
          color: gray
```

**Screenshots**
![image](https://user-images.githubusercontent.com/42458049/99092690-863e5280-25e2-11eb-864d-bfee3173e2d7.png)
![image](https://user-images.githubusercontent.com/42458049/99092747-98b88c00-25e2-11eb-96ef-16258a2e11ba.png)

**Version**
v1.6.1
