### ISSUE TITLE
Allow to set explicit value in state mapping

### ISSUE THREAD

**Issue by habitoti** [maxwroc/battery-state-card#179]
Right now it is possible to map a binary low/high battery state sensor to appropriate values (like 90/20) and so get that battery icon be shown as green (high) or red (low). This is already a nice workaround, however it somehow suggests a 90% charge in this case, until it suddenly drops to 20%/low. It would be great to allow for an explicit value display in the mapping to rather go for a "Good"/"Low" style of display that doesn't suggest to "know" the actual charging level.

```
 - entity: binary_sensor.oeq0221477_lowbat
   name: Garden Door
   state_map:
      - from: High
        to: 90
        value_display: 'Good'      <====
      - from: Low
        to: 15
        value_display: 'Low'        <====
```
