### ISSUE TITLE
Battery Level state of 0 presented as 100%

### ISSUE THREAD

**Issue by mvieleers** [maxwroc/battery-state-card#190]
**Describe the bug**
When the battery level of an entity is 0, the card presents the battery level as 100%

**How to reproduce**
Add a battery level entity to the card.
Using Developer Tools, change the state of the entity to 0 and watch the presentation on the card.

**Expected behavior**
When the state of the entity is 0, it should present as 0% on the card

**YAML configuration**
```yaml

# please paste here your card config
      - type: 'custom:battery-state-card'
        title: Status Batterijen
        sort_by_level: asc
        collapse: 15
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
        state_map:
          - from: 'off'
            to: 100
          - from: 'on'
            to: 1
          - from: true
            to: 1
          - from: false
            to: 100
        bulk_rename:
          - from: Battery Level
          - from: Battery level of
          - from: battery level
          - from: Battery
        entities:
          - entity: lock.garage
            attribute: battery_critical
        filter:
          include:
            - name: attributes.device_class
              value: battery
          exclude:
            - name: entity_id
              value: sensor.solaredge*
            - name: state
              value: Charging
            - name: state
              value: Not Charging
```

**Screenshots**

<img width="2021" alt="Schermafbeelding 2020-12-19 om 11 44 57" src="https://user-images.githubusercontent.com/10944296/102687502-da46e300-41ef-11eb-8d24-283794236f6f.png">
<img width="1996" alt="Schermafbeelding 2020-12-19 om 11 45 35" src="https://user-images.githubusercontent.com/10944296/102687503-dd41d380-41ef-11eb-8376-ef71b569534e.png">
<img width="1948" alt="Schermafbeelding 2020-12-19 om 11 46 14" src="https://user-images.githubusercontent.com/10944296/102687509-e03cc400-41ef-11eb-9ebe-e0c2e549c326.png">

**Version**

v1.6.2
