### ISSUE TITLE
Is there any chance I can filter out any entity created by one specific integration (rfxtrx in my case)?

### ISSUE THREAD

**Issue by marcgarciamarti** [maxwroc/battery-state-card#192]
**Describe what is wrong**
I would like to be able to filter out results based on the integration creating the entities

**YAML configuration**
```yaml

# paste your card configuration here

```

**Screenshot**

**Version**

**Comment by maxwroc** [comment]
You can filter entities based on the any informnation which is available for the particular entity (id, state and attributes). If integration doesn't expose its name via attribute then you cant. AFAIR rfxtrx doesn't expose it unfortunatelly. 

Please paste the example entity with its attributes which you want to filter out - maybe we will figure out something

**Comment by maxwroc** [comment]
No response for a month - closing.

**Comment by igorsantos07** [comment]
I'm doing this via the custom-entities card, so it skips everyone's phones (which is their business, not a maintenance task :)

```yaml
type: custom:auto-entities
card:
  title: All batteries
  type: custom:battery-state-card
  sort_by_level: asc
filter:
  include:
    - domain: sensor
      attributes:
        device_class: battery
  exclude:
    - integration: mobile_app
```
