### ISSUE TITLE
Using card as a connection state with red and green icons

### ISSUE THREAD

**Issue by chriscolden** [maxwroc/battery-state-card#206]
Is it possible for me to add a colour when mapping from off to Disconnected and on to Connected?
It doesn't seem to be applying anything its just a black icon. Many Thanks

**YAML configuration**
```yaml

type: 'custom:battery-state-card'
title: Connection Status
sort_by_level: desc
icon: 'hass:server-network'
color_thresholds:
  - value: 'off'
    color: red
  - value: 'on'
    color: green
state_map:
  - from: 'off'
    to: Disconnected
  - from: 'on'
    to: Connected
bulk_rename:
  - from: ' Connection State'
filter:
  include:
    - name: entity_id
      value: '/[a-z]{2}\d{10}_connection_state/'
      operator: matches

```

**Screenshot**

**Version**
1.6.2
