### ISSUE TITLE
Collapse value ignored when sort_by_level: asc is set

### ISSUE THREAD

**Issue by pschmitt** [maxwroc/battery-state-card#213]
**Describe the bug**
When setting both `collapse: 5` and `sort_by_level: asc` in the config the value of collapse seems to be ignored (as if set to 0).

![image](https://user-images.githubusercontent.com/37886/106860539-d3ebc800-66c4-11eb-9cd1-143976529b90.png)

**How to reproduce**
Set both `collapse: INT` and `sort_by_level: asc` in your config.

**NOTE:** Sorting by `desc` works as expected:
![image](https://user-images.githubusercontent.com/37886/106860402-a272fc80-66c4-11eb-8ed3-29ffae8fa305.png)

**Expected behavior**
I expected `collpase: INT` to work as mentioned in [the documentation](https://github.com/maxwroc/battery-state-card#sorted-list-and-collapsed-view), regardless of the sort order.

**YAML configuration**
```yaml
type: 'custom:battery-state-card'
title: "\U0001F50B Battery Levels"
collapse: 5
sort_by_level: asc
filter:
  include:
    - name: entity_id
      value: '*battery_level*'
    - name: attributes.device_class
      value: battery
    - name: attributes.battery_level
  exclude:
    - name: state
      value: Unknown
      operator: =
    - name: state
      value: Unavailable
      operator: =
    - name: entity_id
      value: '*battery_health'
    - name: entity_id
      value: '*battery_state'
    - name: entity_id
      value: '*_motion_sensor_light_level'
    - name: entity_id
      value: '*_motion_sensor_temperature'
    - name: entity_id
      value: sensor.nimbus_battery_level
    - name: entity_id
      value: binary_sensor.wall_switch_left_*
    - name: entity_id
      value: binary_sensor.wall_switch_right_*
bulk_rename:
  - from: battery level
    to: ''
  - from: Battery Level
    to: ''
  - from: motion sensor motion
    to: motion sensor
  - from: (Both)_
    to: ''
tap_action:
  action: more-info
```

**Version**
1.6.3
