### ISSUE TITLE
Feature: Enable state remapping with included groups

### ISSUE THREAD

**Issue by scyto** [maxwroc/battery-state-card#233]
**Is your feature request related to a problem? Please describe.**
I am using filters to create a dynamic card.
I have two types of device - one where off = batterydead and one where on = battery dead (thanks insteon!)
I would like to apply opposite state mappings for this two groups

**Describe the solution you'd like**
I would like to be able to do something like this:

```
type: 'custom:battery-state-card'
title: Battery Low
sort_by_level: dsc
filter:
  include:
    - name: entity_id
      value: '*_battery_percent'
    - name: entity_id
      value: '*_battery_level'
    - name: entity_id
      value: '*_battery'
    - name: entity_id
      value: 'heartbeat'
      state_map:
        - from: 'on'
          to: 0
        - from: 'off'
          to: 100
    - name: entity_id
      value: '*inverse-heartbeat*'
      state_map:
        - from: 'on'
          to: 100
        - from: 'off'
          to: 0

```

**Additional context**

**Comment by maxwroc** [comment]
I agree it might be useful but unfortunatelly can be quite hard/impossible to implement with the current way how card code works.

I will think about this little bit more hence I will keep this issue open for a bit more but I think I will have to close it later. Sorry

**Comment by scyto** [comment]
Thanks for considering it, appreciate it.
I guess the easiest way is to just make a second card for these devices :-)  especially as it is dynamic card.

**Comment by maxwroc** [comment]
I think that we could solve it in the following way. Instead of applying state-map to a group we can apply it conditionally. This way the solution will be more generic - useful in other cases too (e.g. when someone wants the same functionality but don't want to have groups).

The setting can be something like:
```yaml
state_map:
  - from: "on"
    to: 100
    condition: "{entity_id|contains(inverse)}"
```
