### ISSUE TITLE
Add a common tap_action

### ISSUE THREAD

**Issue by darylvL** [maxwroc/battery-state-card#255]
**Is your feature request related to a problem? Please describe.**
I'd like to define an action for every entity found by the filter.

**Describe the solution you'd like**
Allow a common action for all entities (similarly to how charging state works).

**Additional context**
A possible config would look like this
```
type: 'custom:battery-state-card'
title: Phones & Tablets
sort_by_level: asc
tap_action:
  - action: more-info
filter:
  include:
    - entity_id: device_tracker*
...
```

**Comment by jackwilsdon** [comment]
It seems like this is already supported:
```
type: 'custom:battery-state-card'
filter:
  include:
    - name: attributes.device_class
      value: battery
tap_action: more-info
```
