### ISSUE TITLE
Remove Title for vertical stack cards

### ISSUE THREAD

**Issue by ttaidapos** [maxwroc/battery-state-card#26]
Any way to remove title/name completely in a vertical stack?  Below i'm using a custom vertical-stack-in-card but it has the same behavior.  I put a blank title for now but the gap is large.

![image](https://user-images.githubusercontent.com/27898709/80624079-c9532280-8a10-11ea-81ed-31571876e9f2.png)

```
cards:
  - entities:
      - entity: sensor.dark_sky_precip_probability_0d
      - entity: input_boolean.modem_reboot
    type: entities
  - entities:
      - entity: sensor.atrium_door_battery_level
        name: Atrium Door
      - entity: sensor.baby_room_dimmer_battery_level
        name: Nursery Dimmer
    name: []
    sort_by_level: asc
    collapse: 1
    color_thresholds:
      - value: 5
        color: red
      - value: 10
        color: yellow
    type: 'custom:battery-state-card'
type: 'custom:vertical-stack-in-card'
```
