### ISSUE TITLE
"state_map" attribute together with "filter include"

### ISSUE THREAD

**Issue by msanchezt** [maxwroc/battery-state-card#272]
This is my current card setup, as you can see I'm using the filter include option which is very useful.

![image](https://user-images.githubusercontent.com/6965401/120150824-d29e5800-c1eb-11eb-96aa-ac08116392a6.png)

I would like to add the "state_map" option to convert some values (High --> 100%, Medium --> 50%), but it looks to me that with the filter option is not supported:

```
    state_map:
      - from: "High"
        to: 100
      - from: "Medium"
        to: 50
```

Any thoughts?

**Version**
I'm using latest version available on HACS.
