### ISSUE TITLE
How to show 'Low power mode' in secondary_info?

### ISSUE THREAD

**Issue by alexisteleco** [maxwroc/battery-state-card#277]
First of all, thanks for this piece of code, is really simple to configure and packs an amazing amount of usefulness.

**Describe what is wrong**
I would like to use the [`secondary_info`](https://github.com/maxwroc/battery-state-card#secondary-info) to show wether an iPhone is in low power state or not, and I am not sure how to do this or if this is even possible.

Take into account that the information is an attribute of the `battery_state` entity, not the same as the entity that shows the amount of battery left.

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Baterías
secondary_info: last_updated
sort_by_level: asc
collapse: 4
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: sensor.iphone_alexis_battery_level_2
    name: iPhone Alexis
    secondary_info: "<Here, I would like to see the attribute low_power_mode of the sensor sensor.iphone_alexis_battery_state_2>"
    charging_state:
      entity_id: sensor.iphone_alexis_battery_state_2
      state: Charging
```

**Screenshot**
When not charging:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/17027081/121486502-7c8e9900-c9d1-11eb-9e5e-f9cd341378cf.png">

When charging:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/17027081/121486750-b8296300-c9d1-11eb-9f0f-0f6b4217de9f.png">

And the attribute I would like to extract and show:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/17027081/121487091-09395700-c9d2-11eb-9e54-d1a7fbb1fd96.png">

**Version**
1.6.4

**Comment by maxwroc** [comment]
You can achieve it but you won't be able to display there custom text when it is charging (if you were doing it already). 

You can use `charging_state` object for it - please take a look at the example here https://github.com/maxwroc/battery-state-card#secondary-info

```yaml
type: custom:battery-state-card
name: Secondary info
secondary_info: last_updated # applied to all entities which don't have the override
entities:
  - entity: sensor.bedroom_motion_battery_level
    name: "Bedroom motion sensor"
  - entity: sensor.mi_robrock
    secondary_info: charging # only appears when charging is detected
    charging_state:
      attribute:
        name: "is_charging"
        value: true
      secondary_info_text: "Charging in progress" # override for "Charging" text
  - entity: sensor.jacks_motorola
    name: "Jack's phone"
    secondary_info: "Motorola" # Static text
```

Just instead of charging text put there low power one and provide correct entity which has that signal

**Comment by alexisteleco** [comment]
Hi, sorry for the delay.

I tried with the `charging_state`, nevertheless, it is not working. I think the problem is that the attribute I want to show is not contained in the same entity as the battery level:
The `sensor.iphone_alexis_battery_level_2` is where the battery **level** can be found, whereas the `sensor.iphone_alexis_battery_state_2` is where the battery **state** and the "Low Power Attribute" are.

To take an example, I can use the "Entity Card" to get the attribute I want:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/17027081/123607631-5bfe7580-d7fe-11eb-9a29-a520bbb51540.png">
But I am not able to get the same information as secondary text in the "battery card".

Am I doing something wrong?, I leave here my configuration with the changes you mentioned (I tested with both sensor types, battery **state** and battery **level**):
```yaml
type: custom:battery-state-card
title: Baterías
secondary_info: last_updated
entities:
  - entity: sensor.iphone_alexis_battery_level_2
    name: iPhone
    secondary_info: secondary_info_text
    charging_state:
      attribute:
        name: Low Power Mode
        value: true
      secondary_info_text: Low power
  - entity: sensor.iphone_alexis_battery_state_2
    name: Low power iPhone
    secondary_info: Normal
    charging_state:
      attribute:
        name: Low Power Mode
        value: true
      secondary_info_text: Low power
```

<img width="970" alt="image" src="https://user-images.githubusercontent.com/17027081/123608214-db8c4480-d7fe-11eb-8718-9c6b4b214751.png">


The two cards can be seen here:
<img width="521" alt="image" src="https://user-images.githubusercontent.com/17027081/123608315-ee9f1480-d7fe-11eb-9fa4-23ae59767383.png">

**Comment by maxwroc** [comment]
It wasn't configured correctly. Try the following:

```yaml
type: custom:battery-state-card
title: Baterías
secondary_info: last_updated
entities:
  - entity: sensor.iphone_alexis_battery_level_2
    name: iPhone
    secondary_info: charging
    charging_state:
      entity: sensor.iphone_alexis_battery_state_2
      attribute:
        name: low_power_mode
        value: true
      secondary_info_text: Low power
```

**Note:** please double check the attribute name (I'm pretty sure that it doesn't contain spaces). You can see the actual one in DeveloperTools
![image](https://user-images.githubusercontent.com/8268674/123610041-1fc81680-d7f8-11eb-81ed-9b4b8a14a2d7.png)
