### ISSUE TITLE
Battery state card combined with entity-filter can produce empty card

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#29]

**Comment by ttaidapos** [comment]
I don't have the "render empty card" issue.  Below 1st set is when i have the filter showing 1 entity and 2nd with zero.

```
type: 'custom:vertical-stack-in-card'
cards:
  - entities:
      - entity: sensor.internet_status
        icon: 'mdi:web'
        name: Internet
      - entity: sensor.modem_status
        icon: 'mdi:access-point'
        name: Modem
      - entity: sensor.router_status
        icon: 'mdi:router-wireless'
        name: Router
      - entity: sensor.nas_status
        icon: 'mdi:nas'
        name: NAS
      - entity: sensor.certificate
        tap_action:
          action: call-service
          service: browser_mod.more_info
          service_data:
            entity_id: sensor.ssl_certificate_expiry
      - entity: sensor.home_assistant_v2_db
        icon: 'mdi:database'
        name: Database Size
      - entity: sensor.hass_update
        icon: 'mdi:package-up'
      - entity: sensor.version_available
        icon: 'mdi:new-box'
        name: Available Version
      - entity: sensor.uptime
      - entity: automation.internet_health
        icon: 'mdi:autorenew'
        name: Internet Self Heal
      - entity: input_boolean.modem_reboot
        icon: 'mdi:access-point'
        name: Modem Reboot
      - entity: input_boolean.router_reboot
        icon: 'mdi:router-wireless'
        name: Router Reboot
    show_header_toggle: false
    title: System Status
    type: entities
  - type: entity-filter
    show_empty: false
    entities:
      - entity: sensor.water_battery_level
        name: Laundry Water Sensor
      - entity: sensor.front_door_keypad_battery
        name: August Keypad
      - entity: sensor.front_door_battery
        name: August Door Lock
    state_filter:
      - operator: <=
        value: 50
    card:
      type: 'custom:battery-state-card'
      color_thresholds:
        - value: 50
          color: red
```


![image](https://user-images.githubusercontent.com/27898709/80811632-e6603080-8b8b-11ea-80ec-161a9181e9c7.png)

```
type: 'custom:vertical-stack-in-card'
cards:
  - entities:
      - entity: sensor.internet_status
        icon: 'mdi:web'
        name: Internet
      - entity: sensor.modem_status
        icon: 'mdi:access-point'
        name: Modem
      - entity: sensor.router_status
        icon: 'mdi:router-wireless'
        name: Router
      - entity: sensor.nas_status
        icon: 'mdi:nas'
        name: NAS
      - entity: sensor.certificate
        tap_action:
          action: call-service
          service: browser_mod.more_info
          service_data:
            entity_id: sensor.ssl_certificate_expiry
      - entity: sensor.home_assistant_v2_db
        icon: 'mdi:database'
        name: Database Size
      - entity: sensor.hass_update
        icon: 'mdi:package-up'
      - entity: sensor.version_available
        icon: 'mdi:new-box'
        name: Available Version
      - entity: sensor.uptime
      - entity: automation.internet_health
        icon: 'mdi:autorenew'
        name: Internet Self Heal
      - entity: input_boolean.modem_reboot
        icon: 'mdi:access-point'
        name: Modem Reboot
      - entity: input_boolean.router_reboot
        icon: 'mdi:router-wireless'
        name: Router Reboot
    show_header_toggle: false
    title: System Status
    type: entities
  - type: entity-filter
    show_empty: false
    entities:
      - entity: sensor.water_battery_level
        name: Laundry Water Sensor
      - entity: sensor.front_door_keypad_battery
        name: August Keypad
      - entity: sensor.front_door_battery
        name: August Door Lock
    state_filter:
      - operator: <=
        value: 5
    card:
      type: 'custom:battery-state-card'
      color_thresholds:
        - value: 50
          color: red
```

![image](https://user-images.githubusercontent.com/27898709/80811694-0db6fd80-8b8c-11ea-8b6b-bb2bc3c922b5.png)
