### ISSUE TITLE
After updating to Home Assistant 2021.7.1 the card stopped working?

### ISSUE THREAD

**Issue by TheQue42** [maxwroc/battery-state-card#293]
**Describe what is wrong**
After update of HA (from previous version) my lovelace started acting up in strange ways. Editing lovelace was an issue (the edit button on cards doesnt show up unless I jump back-and-forth between tabs), and one tab with a few cards was always empty, no matter how many times I refreshed, and cleared the cache.

Just ONCE did I see a strange error in the logs referring to battery-card.js, so I tested and manually removed the reference to the below batterycard-config (which I had to do by manually editing the .storage/lovelace-files since I couldnt see anything in HA GUI). 

On restart, the tab was fine again. No idea what the issue is, but a heads up, just in case.

**YAML configuration**
```yaml
                        {
                            "type": "custom:battery-state-card",
                            "title": "Battery levels",
                            "sort_by_level": "asc",
                            "entities": [
                                "sensor.sm_g975f_battery_level",
                                "sensor.sm_g986b_battery_level"
                            ],
                            "collapse": 5,
                            "filter": {
                                "include": [
                                    {
                                        "name": "entity_id",
                                        "value": "*_battery_level"
                                    }
                                ],
                                "exclude": [
                                    {
                                        "name": "entity_id",
                                        "value": "*low_battery_level"
                                    }
                                ]
                            }
                       }
```

**Screenshot**

**Version**

Latest release. Running HA Container.

**Comment by maxwroc** [comment]
I'm on exactly the same version and everything works fine.

In general I think my card cannot break the other functionality on the lovelace UI (like you are describing - missing edit button) so something else is going on I think. Since you know how to fix it can you please try reenabling my card to double check if the issue comes back?

**Comment by TheQue42** [comment]
I should of course have checked that myself (re-adding the code-snippet) but it was getting late :-) 

I just did though, and wham, after saving that tab is empty again! I also doublechecked the sha1sum of my battery-files in /local/plugins/, and they ARE the same!

**Comment by maxwroc** [comment]
Do you see anything (errors) in browser dev console? Can you please paste the screenshot how exactly it looks


> I also doublechecked the sha1sum of my battery-files in /local/plugins/, and they ARE the same!

I don't know what do you mean by this. What kind of battery-files?

**Comment by TheQue42** [comment]
Just the .js file itself, and its map file...

**Comment by TheQue42** [comment]
Ok, now we're on to something.... and as a teacher of troubleshooting...#&%"!&/%"!&#

I did do one **other** change at while I was updating HA yesterday. I changed the names/prefix of my mobile_app entities.

So the card with:

```
type: custom:battery-state-card
title: Battery levels
sort_by_level: asc
entities:
- sensor.sm_g975f_battery_level
- sensor.sm_g986b_battery_level
collapse: 5
filter:
  include:
  - name: entity_id
    value: "*_battery_level"
  exclude:
  - name: entity_id
    value: "*low_battery_level"
```
Actually contains the g986b entity above, that **doesn't** exist anymore. If I remove that from the list, the problem goes away.

But I am still a bit confused, that a reference to a non existing entity will CLEAR the entire tab in lovelace? I would have expected that specific card to become empty, or throw errors, but it clears the whole tab, and therby also hiding the edit button so that I can fix the error.

(The firefox dev console didnt add anything to its output on the save of the lovelace config, with the offending entitity)

(The issue with the edit-button disappearing, is not something that I think has anything to do with this card)
