### ISSUE TITLE
Battery group mdi icon color 

### ISSUE THREAD

**Issue by LiquidBlackNL** [maxwroc/battery-state-card#295]
**Describe what is wrong**
I've set up 2 battery groups (Rookmelders & Contactsensoren) and did assign a MDI icon to them.
But the color of this icon is #212121 instead of the HA default color #44739E.
I can't find an option to change this in the documentation.

Is this by design / default or do I miss something?

**YAML configuration**
```
type: custom:battery-state-card
title: Batterij niveaus
sort_by_level: asc
collapse:
  - name: 'Rookmelders (min: {min}%, aantal: {count})'
    secondary_info: Batterij niveaus {range}%
    icon: mdi:smoke-detector
    entities:
      - sensor.garage_rookmelder_battery
      - sensor.hal_1everdieping_rookmelder_battery
      - sensor.hal_beganegrond_rookmelder_battery
      - sensor.keuken_rookmelder_battery
      - sensor.kleinekamer_rookmelder_battery
      - sensor.meterkast_rookmelder_battery
      - sensor.serre_rookmelder_battery
      - sensor.slaapkamer_rookmelder_battery
      - sensor.studeerkamer_rookmelder_battery
      - sensor.woonkamer_rookmelder_battery
      - sensor.zolder_rookmelder_battery
  - name: 'Contactsensoren (min: {min}%, aantal: {count})'
    secondary_info: Batterij niveaus {range}%
    icon: mdi:leak
    entities:
      - sensor.buiten_brievenbus_contact_boven_battery
      - sensor.buiten_brievenbus_contact_onder_battery
      - sensor.garage_poort_contact_boven_battery
      - sensor.garage_poort_contact_onder_battery
      - sensor.slaapkamer_kledingkast_contact_links_battery
      - sensor.slaapkamer_kledingkast_contact_midden_battery
      - sensor.slaapkamer_kledingkast_contact_rechts_battery
      - sensor.zolder_dakraam_contact_battery
```
    
**Screenshot (Light Mode)**
![image](https://user-images.githubusercontent.com/50137101/125797775-d3baebd0-d319-4847-842b-cdf383fa26c9.png)

**Screenshot (Dark Mode)**
![image](https://user-images.githubusercontent.com/50137101/125798758-a5a0c1fb-cc59-4791-87cf-3d8e525af9fe.png)

**Version**
v1.6.4
