### ISSUE TITLE
Support for binary battery sensors 

### ISSUE THREAD

**Issue by tam1m** [maxwroc/battery-state-card#3]
I have some Osram motion sensors which only report a `battry_low` attribute which either be `on` or `off`. So it would be nice to have support for binary sensors.

**Comment by mdegat01** [comment]
Second this.  I have similar problem Nest Protect devices.  You can see in [the doc](https://www.home-assistant.io/integrations/nest/#sensor) they report their state in the form of a `battery_health` sensor which either has state `Ok` or `Replace`.

I worked around it by combining this card [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) like this:
```yaml
- card:
    show_header_toggle: false
    title: Battery levels
    type: 'custom:battery-state-card'
    color_gradient:
      - '#ff0000'
      - '#ffff00'
      - '#00ff00'
  filter:
    exclude:
      - state: Ok
    include:
      - entity_id: sensor.*_battery_level
      - entity_id: sensor.*_battery_health
  show_empty: false
  sort:
    method: state
    numeric: true
  type: 'custom:auto-entities'
```
What happens is that the protects don't show up unless their status is `Replace`.  And then since that's not numeric the battery-state-card treats it as `0` for color calculation.

Which works but would be nice if there was a way to support this natively.  Like for entities that report battery in a non-numeric state if I could provide a map between the non-numeric state and a numeric value to use for display (for Nest probably something like `100` for `Ok` and `25` for `Replace`)

Great card though!  Really like it
