### ISSUE TITLE
add the charging status automatically based on "charging" attribute

### ISSUE THREAD

**Issue by finity69x2** [maxwroc/battery-state-card#31]
I don't know if it's possible but since I am using the "auto-entities" card to populate this card it would be nice if this card could automatically check to see if the entity has a way to check that the battery is charging or not.

Otherwise there is no way that I know of to use the "auto-entities" and then also set the charging status.

Right now I have two entities that show charging status - one uses a "Battery State: Charging/Not Charging" attribute (IOS mobile app) and the other uses an "is_charging: true/false" attribute (Android mobile app).

**Comment by kyotodesertfox** [comment]
Hopefully this might help you, as I think that I was trying to do the same thing. My phone battery entity has the charge % listed as the State, and an "is_charging" attribute, a value of true / false.

What I wound up doing is creating a new sensor, and defining the state manually using a template:

configuration.yaml:

```
- platform: template
    sensors:
      battery_pixel:
        friendly_name: Pixel 4 XL Charging Status
        unit_of_measurement: '%'
        value_template: >-
          {%- if state_attr('sensor.pixel_4_xl_battery_level', 'is_charging') %}
            is_charging
          {% else %}
            not_charging
          {% endif %}
        device_class: battery
```

UI Card:

```
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - charging_state:
      entity_id: sensor.battery_pixel
      state: is_charging
    entity: device_tracker.pixel_4_xl
    name: My Pixel 4 XL
title: Battery Levels
type: 'custom:battery-state-card'

```
