### ISSUE TITLE
Use of separate entities for charging state at card config level

### ISSUE THREAD

**Issue by CDRX2** [maxwroc/battery-state-card#314]
Using a secondary entity for charging state is already possible at the individual entity level. However, this feature is not yet applicable at a card config level.

I suppose having something similar to the filter function but for charging state could be a possible approach.

**Comment by CDRX2** [comment]
I would imagine something like this:
```
charging_filter:
  include: # filters for auto-adding charging states
    - name: entity_id # entities which id ends with "_is_charging"
      value: "*_is_charging"
```
