### ISSUE TITLE
Help with charging state from attribute please

### ISSUE THREAD

**Issue by xbmcnut** [maxwroc/battery-state-card#316]
Can't seem to pull attribute value into card. The bottom entity on my screenshot should show the tablet as charging as the value for the attribute `charging` is currently `true`? Did I do something wrong?

```
- entity: sensor.samsung_tab10_battery
  charging: # uses charging attribute on sensor.samsung_tab10_battery
    attribute:
      name: charging
      value: 'true'
```

**Screenshot**
![image](https://user-images.githubusercontent.com/1492137/132969970-a916b565-dc1f-4c1c-afd5-baabd780cdf8.png)

**Version**
1.6.4

**Comment by maxwroc** [comment]
what if you use
```yaml
value: true
```

**Comment by xbmcnut** [comment]
> what if you use
> 
> ```yaml
> value: true
> ```

Thanks, but that does not work either.

**Comment by maxwroc** [comment]
Please follow the examples from here:
https://github.com/maxwroc/battery-state-card#charging-state-indicators

There is no such a thing like "charging" property in entity. It should be "[charging_state](https://github.com/maxwroc/battery-state-card#common-options)" instead

**Comment by xbmcnut** [comment]
Thanks for the reply. I've changed the code as I mistakenly thought the attribute was charging_state which it's not. I've amended the code below but the charge icon still does not appear when the attribute `charging` for my sensor `sensor.samsung_tab10_battery` turns `true`.

```
   - entity: sensor.samsung_tab10_battery
     tap_action: more-info
     charging_state:
       attribute:
         name: "charging"
         value: "true"
```

![image](https://user-images.githubusercontent.com/1492137/133171904-d87608e8-1538-4b2f-9c59-e63b6e815015.png)

![image](https://user-images.githubusercontent.com/1492137/133171962-50b95c1f-05b7-4422-981f-00561a0eed4f.png)

**Comment by xbmcnut** [comment]
I created a workaround my making another sensor.
```
    samsung_tab10_charging_state:  
      friendly_name: "Tablet Charging"
      value_template: "{{ state_attr('sensor.samsung10_fkb_tabletui', 'charging') }}" 
```
```
  - entity: sensor.samsung_tab10_battery
    tap_action: more-info
    charging_state:
      entity_id: sensor.samsung_tab10_charging_state
      state: 'True'
```
