### ISSUE TITLE
how to assign tap_action to entities listed by a filter

### ISSUE THREAD

**Issue by paulius2k** [maxwroc/battery-state-card#331]
Hello,
thank you for this card!

I have a question: I listed my entities using a filter as per this example:
```
filter:
  include: # filters for auto-adding
    - name: entity_id # entities which id ends with "_battery_level"
      value: "*_battery_level"
```

How can I assign `tap_action: more-info` to these entities?
