### ISSUE TITLE
Feature: support for default icon / icon from attribute

### ISSUE THREAD

**Issue by pachi81** [maxwroc/battery-state-card#336]
Hi,

I have an entity which have battery_level and battery_icon attribute. The battery_level attribute is supported, but I have not found any solution, to use the icon-attribute.

I found one solution to create a battery sensor with the corresponding icon from the attributes using templates:
```
  - platform: template
    sensors:
       my_battery:
         friendly_name: 'My Battery'
         value_template: '{{ states.my_entity_id.attributes.battery_level}}'
         unit_of_measurement: '%'
         entity_id: my_entity_id
         icon_template: '{{ states.my_entity_id.attributes.battery_icon }}'
```
But I found also no solution to use the default icon of the entity!?

Is one of both solutions possible to implement?

Thank you!
