### ISSUE TITLE
Zigbee2mqtt changes affecting card usage

### ISSUE THREAD

**Issue by Kosygor** [maxwroc/battery-state-card#337]
**Is your feature request related to a problem? Please describe.**
Zigbee2mqtt [creator ](https://github.com/Koenkk/zigbee2mqtt/pull/7684) addon removed additional separate entities. That inxludes entity_id_battery and entity_id_linkquality. But not all them. It still 3 entities for sensors like Xiomi Humidity / Temperature / Pressure.

**Describe the solution you'd like**
Way of filtering duplicated entires to card. 

**Additional context**
When You filter devices by:
```filter:
  include:
    - name: attributes.battery
```
It makes few duplicates and most of people use this card to automate things.

**Comment by maxwroc** [comment]
Sorry but I don't understand the problem. Maybe paste some screenshots or try to descrie in a little bit different way.

If I understood correct Franks change it removes/disables some entities automatically. I don't understand how such change can produce duplicates in my card when you use filters.

I don't use zigbee2mqtt so I won't be able to reproduce the issue myself.

If you want me to help please provide listings of entities and their attrubutes - the ones which are duplicated

**Comment by Kosygor** [comment]
Ok so here is my config:
```
entities: null
filter:
  include:
    - name: attributes.battery
  exclude:
    - name: entity_id
      value: sensor.XXX # and few that I have excluded manually. 
    - name: state
      value: 60
      operator: '>'
sort_by_level: asc
type: custom:battery-state-card
```
Since there is no battery entities generated for individual devices We have to dig trough attributes and this causes same devices being listed multiple times, with different entities (and they were not in the group excluded by frenck). Effect:
![image](https://user-images.githubusercontent.com/61921662/146234030-756435ea-192e-4b8e-b4ea-28e9c5ca8635.png)
And this turns really good self listing card into:
1. Have to exclude everything that it have listed card
2. Have to include everything by hand card.
Cannot find any trick to pass by that.
