### ISSUE TITLE
tap_action: more-info seems not working

### ISSUE THREAD

**Issue by pmazz** [maxwroc/battery-state-card#34]
Hi,
is it me, or the `tap_action: more-info` is not working?
Nothing seems to happen when clicked...

**YAML configuration**
```yaml
      - id: main.batteries
        type: custom:battery-state-card
        name: Batteries
        entities:
          - entity: sensor.cell_paolo_battery
            name: Paolo's Phone
            charging_state:
              entity_id: sensor.cell_paolo_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
          - entity: sensor.cell_silvia_battery
            name: Silvia's Phone
            charging_state:
              entity_id: sensor.cell_silvia_charging
              state: "True"
              color: var(--paper-item-icon-active-color)
        color_thresholds:
          - value: 15
            color: Crimson
          - value: 30
            color: Gold
          - value: 100
            color: var(--paper-item-icon-color)
        tap_action: more-info
```

**Screenshot**
![image](https://user-images.githubusercontent.com/44721151/80908951-75a04c00-8d24-11ea-95f7-ae7a1fbb80db.png)
Not very useful...

**Version**
v1.1.1

Thanks !
