### ISSUE TITLE
v2.0.0 broke collapse section

### ISSUE THREAD

**Issue by bcutter** [maxwroc/battery-state-card#349]
**Describe the bug**
After updating to latest 2.0.0 release a collapse/expand section is added to every card (which is of course non-functional because there are no elements to be shown), even if it's not needed because there are not more elements than the number set in "collapse" config.

**How to reproduce**
1) Update to 2.0.0
2) Add a card with X elements, set "collapse" to at least X minus 1.

**Expected behavior**
Collapse section is only shown if more elements than set in collapse config.

**YAML configuration**
```
type: custom:battery-state-card
entities:
  - entity: group.batterystate_switches
title: 🔲 Schalter
secondary_info: last_updated
tap_action: more-info
sort_by_level: asc
collapse: 7
filter: 0
color_thresholds:
  - value: 20
    color: red
  - value: 45
    color: yellow
  - value: 100
    color: green
bulk_rename:
  - from: ' Battery Level'
    to: ''
  - from: ' Akkufüllstand'
    to: ''
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13799156/146796925-529ae2e9-d18c-46df-ab53-28729ba1a00b.jpeg)

**Version**
2.0.0
