### ISSUE TITLE
Tap action 'more-info' is not working anymore

### ISSUE THREAD

**Issue by sermayoral** [maxwroc/battery-state-card#351]
I had tap_action: more-info working great but besides 2.0.0, it is not working anymore :-(.

I had tested this as well (as breaking changes said) with no success:

```yaml
type: custom:battery-state-card
title: Vibración
entities:
  - entity: sensor.bateria_vibracion_buzon
    name: Buzón
    tap_action: more-info
    type: custom:battery-state-entity
```

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Movimiento
entities:
  - entity: sensor.bateria_movimiento_cocina
    name: Cocina
    tap_action: more-info
```

**Screenshot**

**Version**

2.0.1
