### ISSUE TITLE
Charging State from iCloud Devices

### ISSUE THREAD

**Issue by kurim** [maxwroc/battery-state-card#356]
Based on attributename and value it should switch to charging icon but, this does not happen.

**YAML configuration**
```yaml

type: custom:battery-state-card
title: Charging indicators
charging_state:
  attribute:
    - name: Battery status
      value: Charging
entities:
  - sensor.nyan_battery_state
  - sensor.nyan_mini_battery_state
  - sensor.nyan_watch_battery_state
color_gradient:
  - '#ff0000'
  - '#f8ff33'
  - '#00ff00'
tap_action: more-info
```

**Screenshot**
Battery State Card:
![image](https://user-images.githubusercontent.com/1880220/147350792-a9b8785c-1670-473d-ae29-b0ba34602b69.png)
Entities Card:
![image](https://user-images.githubusercontent.com/1880220/147350797-d1b09198-50db-4bd3-9203-71cd990f1bb6.png)

Attributes:
![image](https://user-images.githubusercontent.com/1880220/147350949-050d730a-ed11-4db8-af88-6feadc657cc0.png)

**Version**
2.0.2
