### ISSUE TITLE
Support for deeper nested charging attributes

### ISSUE THREAD

**Issue by syphernl** [maxwroc/battery-state-card#362]
**Is your feature request related to a problem? Please describe.**

Some devices have nested attributes, such as Valetudo-based vacuums. 
For instance, the charging state is placed in the `valetudo_state` attribute, which has an `id` and `name` in it: 

```
{'id': 8, 'name': 'Charging'}
```

I have tried this in the card config:

```yaml
            charging_state:
              attribute:
                name: "valetudo_state.name"
                value: "Charging"
```

But unfortunately it does not work.

**Describe the solution you'd like**

It would be nice if this card could somehow obtain "deeped nested" attributes, without needing to create a template sensor to extract this particular value.

**Additional context**
