### ISSUE TITLE
Can't get charging state to show

### ISSUE THREAD

**Issue by floli** [maxwroc/battery-state-card#378]
Hello,
I have this YAML to embed the battery state card into my dashboard:
```yaml
type: custom:battery-state-card
title: Ladestand
entities:
  - entity: sensor.handy_florian_battery_level
    charging-state:
      entity_id: binary_sensor.handy_florian_is_charging
      icon: mdi:flash
      state: 'on'
```
Display of battery state works fine, but charging state is ignored, i.e., no visual indication. The entity `binary_sensor.handy_florian_is_charging` is correct (copy & pasted it directly into the state overview) and is verified `on` when charging.

Anything I am missing here?

Thanks!

**Comment by maxwroc** [comment]
Can you please paste the screenshot of the *_is_charging entity listing (wrist state and attributes) from developer tools

**Comment by floli** [comment]
![grafik](https://user-images.githubusercontent.com/1028028/148699243-285b2df0-98bd-4485-8870-8dc0e70a74be.png)

**Comment by OddSquirrel** [comment]
Installed the card the other day and can confirm that there is no charging indication on my battery icon, either.
Battery state is accurate and the charging state is being reported in the entity, it just doesn't alter the representation of the battery state icon.

**Comment by maxwroc** [comment]
@floli there is a mistake on your config in `charging_state` should be underscore not dash

**Comment by floli** [comment]
> @floli there is a mistake on your config in `charging_state` should be underscore not dash

Ar, now it works:

```yaml
entities:
  - entity: sensor.handy_florian_battery_level
    charging_state:
      entity_id: binary_sensor.handy_florian_is_charging
      state: 'on'
```

@OddSquirrel Do you have similar fault? For me, that issue can be closed, problem was between keyboard and chair.
