### ISSUE TITLE
Folded card doesn't.show all entities

### ISSUE THREAD

**Issue by fabricioavil** [maxwroc/battery-state-card#39]
**Describe the bug**
If I use the folded option, some/many entities are not seen in the folded items, maybe because I have too many entities? The folded options is possibly limiting the numbers of items being collapsed (I see 21 folded items plus the 10 unfolded). It was easy to notice because when folded, it shows only one 100% entity, but I have many more items with 100%.

**How to reproduce**
Set to folded and compare the number of entities.

**Expected behavior**
Show all entities as shown when not folded.

**YAML configuration**
```yaml
                            "card": {
                                "collapse": 10,
                                "color_thresholds": [
                                    {
                                        "color": "#de2d0d",
                                        "value": 25
                                    },
                                    {
                                        "color": "#f4b400",
                                        "value": 50
                                    },
                                    {
                                        "color": "#0da035",
                                        "value": 100
                                    }
                                ],
                                "name": "Battery level",
                                "show_header_toggle": false,
                                "sort_by_level": "asc",
                                "type": "custom:battery-state-card"
                            },
                            "filter": {
                                "exclude": [
                                    {
                                        "entity_id": "*battery*level*"
                                    },
                                    {
                                        "entity_id": "*protect_battery_health_state*"
                                    },
                                    {
                                        "entity_id": "sensor.battery_state"
                                    },
                                    {
                                        "domain": "device_tracker"
                                    },
                                    {
                                        "state": "unknown"
                                    }
                                ],
                                "include": [
                                    {
                                        "entity_id": "*battery*",
                                        "options": null
                                    }
                                ]
                            },
                            "type": "custom:auto-entities"
                        },
```

**Version**
Currently 1.2.0, but I have been using it possibly (almost) since you made it available in HACS (great work btw).
