### ISSUE TITLE
Binary Sensors in Groups don't use state mapping

### ISSUE THREAD

**Issue by xstrex** [maxwroc/battery-state-card#403]
**Is your feature request related to a problem? Please describe.**

I've got a group of binary sensors, that all report the same "on", "Off" state, but when placed in a group, the state-mapping isn't used: 
```  
- name: Motion & Leak Sensors
    secondary_info: 'Battery levels (min: {min}%, {count})'
    icon: mdi:percent
    entities:
      - binary_sensor.front_door_heartbeat
      - binary_sensor.patio_door_heartbeat
      - binary_sensor.kitchen_heartbeat
      - binary_sensor.barthroom_heartbeat
      - sensor.motion_battery
    state_map:
      - from: 'Off'
        to: 100
      - from: 'on'
        to: 10
```
This results in something looking like:
![image](https://user-images.githubusercontent.com/12849470/153517421-ce9197a9-e51d-4dca-a6c8-279363663bfc.png)

**Describe the solution you'd like**

Ideally I'd expect the state_map to respect the entities listed in the group, or at least the entities matching the on/Off state; instead it simply reports as "Off" and unknown, when in fact the battery icon should be green, and report 100%. 

**Additional context**

I'm fairly certain this works outside of the group, but not inside the group; I'd hope the behavior would be the same whether it's inside or outside a group. 

Cheers
