### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by neilsleightholm-paxton** [maxwroc/battery-state-card#422]
**Describe what is wrong**
Are the installation instructions correct? I installed via HACS and added the resources section as described (although the path was different) and when restarting HASS I got an error "_The system cannot restart because the configuration is not valid: Integration error: resources - Integration 'resources' not found._". Removing the resources fixed this and didn't seem to affect the operation of the card.

**YAML configuration**
```yaml
resources:
   - url: /config/www/community/battery-state-card/battery-state-card.js
     type: module
```

**Screenshot**

**Version**
v2.1.0
HACS 1.24.3
