### ISSUE TITLE
Support "common options" in filters

### ISSUE THREAD

**Issue by Kilowatt-W** [maxwroc/battery-state-card#448]
It looks like in filters the multiplier is not working.

I added some wifi strength values from my esphome development and these are all in -xx dBm. Because the colors are not working with negative values I would like to multipy with -1 to get some positive values.

```
filter:
  include:
    - name: entity_id
      value: '*signal*'
      multiplier: -1
```
Version in use is 2.1.1

Maybe I missed something and there is a way to use colors in reverse mode so 1 is the most ~ green and 100 is worst ~ red ? Maybe this would be a nice feature request :-)

Thank you for this wonderful peace of software.
