### ISSUE TITLE
V2 broke - no card displayed

### ISSUE THREAD

**Issue by xstrex** [maxwroc/battery-state-card#455]
**Describe what is wrong**
V2 not working 

Not using entities card, and don't think I have any custom styles, though no card did displayed. 

**YAML configuration**
```yaml

type: custom:battery-state-card
sort_by_level: desc
bulk_rename:
  - from: Battery Level
    to: sensor
  - from: Battery
  - from: battery
  - from: Heartbeat
  - from: sensor
  - from: Internal
state_map:
  - from: 'off'
    to: 100
  - from: 'on'
    to: 10
  - from: Unavailable
    to: Offline
filter:
  exclude:
    - name: state
      value: Unavailable
    - name: state
      value: 80
      operator: '>'
collapse:
  - name: Plant Sensors
    secondary_info: 'Battery levels (min: {min}%, {max}%)'
    icon: mdi:leaf
    entities:
      - sensor.moneytree_battery
      - sensor.pearls_battery
      - sensor.pothos_battery
      - sensor.spider_battery
      - sensor.succulent_battery
      - sensor.prayer_battery
  - name: Motion & Leak Sensors
    secondary_info: 'Battery levels (min: {min}%, {count})'
    icon: mdi:percent
    entities:
      - binary_sensor.front_door_heartbeat
      - binary_sensor.patio_door_heartbeat
      - binary_sensor.kitchen_heartbeat
      - binary_sensor.barthroom_heartbeat
      - sensor.motion_battery
      - binary_sensor.zw_003_low_battery
entities:
  - entity: sensor.newt_battery_level
    secondary_info: charging
    name: Roomba
    tap_action:
      action: more-info
  - entity: sensor.macbook_internal_battery_level
    secondary_info: charging
    charging_state:
      entity_id: sensor.macbook_internal_battery_state
      state: Charging
    tap_action:
      action: more-info
  - entity: sensor.macbook_pro_internal_battery_level
    secondary_info: charging
    charging_state:
      entity_id: sensor.macbook_pro_internal_battery_state
      state: Charging
    tap_action:
      action: more-info
  - entity: sensor.jon_iphone_battery_level
    secondary_info: charging
    charging_state:
      entity_id: sensor.jon_iphone_battery_state
      state: Charging
    tap_action:
      action: more-info
  - entity: sensor.jon_ipad_battery_level
    secondary_info: charging
    charging_state:
      entity_id: sensor.jon_ipad_battery_state
      state: Charging
    tap_action:
      action: more-info
  - entity: sensor.sonos_roam_battery
    secondary_info: charging
    charging_state:
      entity_id: binary_sensor.sonos_roam_power
      state: 'on'
    tap_action:
      action: more-info
```

**Screenshot**

**Version**
2.1.1

**Comment by maxwroc** [comment]
Since you are writing about "v2" I assume you haven't updated the card for a while... but the thing is that v2 is available for about 7 months already and no one reported any major problems so I assume there must be something specific in your case.

Can you please check if there are any errors in the dev console in your browser (you can open it by pressing F12)?

I assume you do have some of the entities which battery level is below 80%, right? If not then your "exclude" filter will hide all of them and the card will disappear

**Comment by xstrex** [comment]
Correct, I have been running this for some time now, without issue, then went to look at it the other day, and found the entire card was missing. Yet the yaml shows up in the editor just fine. And yes I have a few devices under 80% that are not chowing up. 

I'll check the browser.

**Comment by xstrex** [comment]
Interesting; so I tried removing and re-adding the component, same result. I Tried going through the options, or blocks of options one by one to see what might be causing it. 

For some reason, the entire above config works, exactly as it should, when I remove this block. 
```yaml
filter:
  exclude:
    - name: state
      value: Unavailable
    - name: state
      value: 80
      operator: ">"
```

I also tried removing each state item, and the entire thing fails, so it's not one, or the other, but a function of the `filter:`. Not sure what yet, but I hope this helps.
