### ISSUE TITLE
Color thresholds for values below 0 (plus optionally allowing >/< syntax)

### ISSUE THREAD

**Issue by bcutter** [maxwroc/battery-state-card#482]
**Is your feature request related to a problem? Please describe.**
With HA Companion app 2022.8 for Android the battery power sensor has been introduced. This gives the current power usage, e. g.:
![grafik](https://user-images.githubusercontent.com/13799156/187081913-0699f406-97a1-4e94-a64e-f0b91fb14a0f.png)
Currently a color threshold can not be set for negative values (<0). Syntactically it's also not possible to work with "great than" and "lower than".

**Describe the solution you'd like**
At least allow negative values to work with color_thresholds. >/< would be an optional nice thing. So either:
```
    color_thresholds:
      - value: <0
        color: red
      - value: 0
        color: yellow
      - value: >0
        color: green
```
or at least
```
    color_thresholds:
      - value: -0.01
        color: red
      - value: 0
        color: yellow
      - value: 0.01
        color: green
```
Currently for negative values the color_threshold is not applied, even if value is set as `0`.

**Additional context**
- [Release notes HA Companion App for Android](https://github.com/home-assistant/android/releases/tag/2022.8.0)
- [Details on new battery power sensor](https://github.com/home-assistant/android/pull/2799)
- [Similar issue related to color threshold setting](https://github.com/maxwroc/battery-state-card/issues/460)
