### ISSUE TITLE
Custom conversion of battery state values

### ISSUE THREAD

**Issue by felislynx-silae** [maxwroc/battery-state-card#490]
**Describe what is wrong**
Sonoff sensors are reporting only a voltage. I would like to map voltage to percentage but i don't know how. I've tried convert, but there was no effect on entities
**YAML configuration**
```yaml
type: custom:battery-state-card
title: Battery levels
entities:
  - entity: sensor.pir_sensor_battery
  - entity: sensor.pir_sensor_2_battery
  - entity: sensor.sonoff_1001038b57_battery_voltage
  - entity: sensor.sonoff_1001038b69_battery_voltage
  - entity: sensor.water_leak_sensor_battery_state
```

I'm using v2.1.1

**Comment by WAPEETY** [comment]
voltage to percentage is not equal for all devices and batteries so it's not an effective and easy feature to implement

**Comment by felislynx-silae** [comment]
@WAPEETY I know, my sensor uses 2xAAA 800 mAh batteries. I would like to have aprox value, not ideal one

**Comment by maxwroc** [comment]
Currently it's not possible to do such a thing with this card alone. You can try to achieve it with help of template sensor. So basically you will have an additional template sensor for you sonoff device in which you will do all necessary calculations and later you can use the result in the battery-state-card.

It is an interesting problem... it might be worth to give user the ability to manipulate the value taken from entity. In fact I have implemented already such functionality in v3 but only for secondary_info. Making it available somewhere else (like entity state) wouldn't be a problem.

I'm tagging this as a v3 TODO item. But I'm really not sure when I'll be able to release this version - it still requires a lot of time to finish. Maybe I will think about publishing beta versions - so you can test/use stuff earlier.

**Comment by felislynx-silae** [comment]
Thank you

**Comment by tigrrr** [comment]
Thanks! That's exactly what i'm also looking for.

**Comment by fireballhh** [comment]
would be great to have that Homematic IP Devices also report Voltage

**Comment by maxwroc** [comment]
Ok I came up with the following approach which should help you.

At the entity level you have a `value_override` setting where you can use "KString" (string which can contain dynamic values - something similar to jinja functions).

Here is an example:
```yaml
type: custom:battery-state-card
entities:
  - entity: sensor.my_device
    value_override: "{state|thresholds(345,880,1000,1200)}"
```

What happens here is that we take the value from the entity "state" (you can specify an attribute too, or even the other entity) and then we pass it to the "thresholds" function (still thinking about a better name - maybe "percentage"?). You can pass as many params to that function as you need.

Since we have passed here 4 values it means that the result value can have 5 different states: 0, 25, 50, 75, 100 (the number of states is always `numbers_count + 1`). Function tries to fit the value into these 5 buckets using the given thresholds so values below 345 will result on 0, values between 345-880 will result in 25 and so on.

There are other simpler functions like `greaterthan`, `lessthan`, `between` which you can combine and achieve similar results. They might be useful when the case is simple.

If you have any suggestions or concerns please let me know.

This will be available in v3.
