### ISSUE TITLE
Wrong values shown for sensors with multiply attributes

### ISSUE THREAD

**Issue by programmdesign** [maxwroc/battery-state-card#499]
**Describe what is wrong**

- I'm using filters, e.g., to get all device temperatures automatically into one card
- The sensors / entities I'm filtering usually have several attributes (temperature, humidity, device temperature, etc.). 
- For some entities, the battery state card plugin shows wrong values in the card.
- Instead of taking the device temperature it shows for example the battery value. 
- If I click on the output of the state card to see more details, I see the correct values though.
- I've tried to also specify the attribute of the sensor, w/o any luck. 

Is there anything I'm missing in terms of the settings or is this maybe a potential bug? Thanks for any help! 

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Sensortemperatur
icon: mdi:thermometer
color_thresholds:
  - value: 25
    color: green
  - value: 35
    color: yellow
  - value: 100
    color: red
tap_action:
  action: more-info
sort_by_level: desc
unit: °C
round: 1
filter:
  include:
    - name: entity_id
      value: sensor.*_device_temperature
  exclude:
    - name: state
      value: 25
      operator: <=
```

**Screenshot**

**Output from battery state card**
<img width="406" alt="image" src="https://user-images.githubusercontent.com/4633284/195660230-660ad9ef-9bab-422d-bcf6-583284309290.png">

**Pop-Up, when I click on the output from the battery state card**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/4633284/195660551-e4012776-8216-4e32-902f-7bc74c3e95b7.png">

**Output from Entity Card for the exact same entity**
<img width="426" alt="image" src="https://user-images.githubusercontent.com/4633284/195660409-994998c7-1eae-4bf5-9b37-5bcfaf5b8d49.png">

**Exposed value of the sensor / entity**
<img width="384" alt="image" src="https://user-images.githubusercontent.com/4633284/195661423-19dd87aa-bfa9-4897-a5da-2fedfca861d4.png">

**Version**
2.1.1

**Comment by maxwroc** [comment]
It's because this card was mainly designed for showing battery state. It automatically takes "battery" attribute value if such exists. If all your devices have the same attributes you can add the `attribute: device_temperature` (at the "unit" level) e.g.:
```yaml
type: custom:battery-state-card
title: Sensortemperatur
icon: mdi:thermometer
color_thresholds:
  - value: 25
    color: green
  - value: 35
    color: yellow
  - value: 100
    color: red
tap_action:
  action: more-info
sort_by_level: desc
unit: °C
attribute: device_temperature
round: 1
filter:
  include:
    - name: entity_id
      value: sensor.*_device_temperature
  exclude:
    - name: state
      value: 25
      operator: <=
```
