### ISSUE TITLE
Mouse hover-over pointer doesn't indicate clickable area in battery-state-entity

### ISSUE THREAD

**Issue by ChristophCaina** [maxwroc/battery-state-card#503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to click on the state of the entity and see the history statistics - like it is for all other entities cards.
Currently, this seems not to work by default.

**Additional context**
```
type: entities
title: Fahrzeug-Batterie
entities:
  - type: custom:battery-state-entity
    entity: sensor.t*****235_battery_level
    name: State of Charge
    charging_state:
      entity_id: switch.t*****235_charging
      state: 'on'
```

**Comment by maxwroc** [comment]
https://github.com/maxwroc/battery-state-card#tap-action

And look at the examples at the bottom of the doc. You can apply the same setting for all of the entities by specifying this action at the root level

**Comment by Christoph-Caina** [comment]
Hi,
thanks for the hint with the documentation.
It seems, that I have overseen that... :-(

But...
Does this also work, if I use the "- type: custom:battery-state-entity" ?

Here's one of my yaml cards:
```
type: entities
entities:
  - entity: sensor.oilfox_of7090001854_validationerror
    name: Validierungsfehler
  - entity: sensor.oilfox_of7090001854_lastmeasurement
    name: letzte Messung
  - type: custom:battery-state-entity
    entity: sensor.oilfox_of7090001854_batterylevel
    name: Batteriezustand
    tap-action:
      action: more-info
state_color: false
```

The last entry in the card is the type custom:battery-state-entity - with a configured tap-action.
But it does not seem to work... ?
