### ISSUE TITLE
Charging State Specific Icons

### ISSUE THREAD

**Issue by kellcomnet2** [maxwroc/battery-state-card#506]
I would like to be able to have different icons depending on the value in state, my devices report state as "Full","Charging","Discharged" and I would like to present different icons depending on which value is returned.
Current Code
```
type: custom:battery-state-card
title: Battery levels
tap_action:
  action: more-info
charging_state:
  state: Charging
  icon: mdi:flash
  color: '#007a0c'
color_gradient:
  - '#a30000'
  - '#ffe100'
  - '#007a0c'
entities:
  - sensor.ups_battery_charge
  - sensor.fsdfsd_battery_state
  - sensor.dsffsdfsd_battery_state
  - sensor.dfgfgd_battery_state
```
