### ISSUE TITLE
I Cant use inclued and exclude filters simultaneously anymore

### ISSUE THREAD

**Issue by ecto1a2003** [maxwroc/battery-state-card#513]
**Describe the bug**
when i use include and exclude filters together all batteries disappear

**How to reproduce**
use include and exclude filters

**Expected behavior**
this was working previously, not sure what happened

**YAML configuration**
```yaml

type: custom:battery-state-card
title: Batteries
sort_by_level: asc
collapse: 5
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
tap_action:
  action: more-info
filter:
  include:
    - name: entity_id
      value: sensor.*batt*
  exclude:
    - name: entity_id
      value: sensor.*health*
    - name: entity_id
      value: sensor.*ford*
    - name: entity_id
      value: sensor.*battery_temperature*
    - name: entity_id
      value: sensor.*battery_power*
entities:
  - entity: sensor.steamdeck_power
    name: SteamDeck
    charging_state:
      entity_id: sensor.steamdeck_power.status
      state: 'on'
  - entity: sensor.jenkins_battery_level
    name: Jenkins Battery Level
    charging_state:
      entity_id: vacuum.jenkins
      status: Charging
  - entity: sensor.no_3113_battery_level
    name: NO-3113 Battery Level
    charging_state:
      entity_id: vacuum.no_3113
      status: Charging
  - entity: sensor.master_bathroom_temp_and_humidity_battery
    name: Bathroom Sonos sensor
  - entity: sensor.garage_temp_and_humidity_battery
    name: Garage Sonos sensor
  - entity: sensor.outdoor_temp_and_humidity_battery
    name: Outdoor Sonos Sensor
  - entity: sensor.master_bedroom_temp_and_humidity_battery
    name: Master Bedroom Sonos sensor
  - entity: sensor.rumpus_room_temp_and_humidity_battery
    name: Rumpus Room Sonos sensor
  - entity: sensor.solarium_temp_and_humidity_battery
    name: Solarium Sonos sensor
  - entity: sensor.attic_temp_and_humidity_battery
    name: Attic Sonos sensor
  - entity: sensor.guest_bathroom_temp_and_humidity_battery
    name: Guest Bathroom Sonos sensor
  - entity: sensor.hue_motion_sensor_1_battery
    name: Rumpus Room Motion
  - entity: sensor.hue_motion_sensor_1_battery_2
    name: Living Room Motion
  - entity: sensor.hue_motion_sensor_1_battery_3
    name: Master Bedroom Motion
  - entity: sensor.hue_motion_sensor_2_battery
    name: Foyer Motion
  - entity: sensor.hue_motion_sensor_2_battery_2
    name: Nursery Motion
  - entity: sensor.hue_motion_sensor_1_battery_4
    name: Hallway Motion
  - entity: sensor.dinning_room_temp_and_humidity_battery
    name: Kitchen Sonos sensor
  - entity: sensor.master_bathroom_temp_and_humidity_battery
    name: Master Bathroom Sonos sensor
  - entity: sensor.nursery_temp_and_humidity_battery
    name: Nursery Sonos sensor
  - entity: sensor.pke_meter_battery_level
    name: PKE Battery
    charging_state:
      entity_id: binary_sensor.pke_meter_is_charging
      state: 'on'
  - entity: sensor.jennie_flip_battery_level
    name: Jennie Flip
    charging_state:
      entity_id: binary_sensor.jennie_flip_is_charging
      state: 'on'
  - entity: sensor.dining_room_vent_battery
    name: Dining room vent battery
  - entity: sensor.foyer_vent_battery
    name: Foyer vent battery
  - entity: sensor.living_room_vent_battery
    name: Living room vent battery
  - entity: sensor.master_bedroom_vent_battery
    name: Master bedroom vent battery
  - entity: sensor.nursery_vent_battery
    name: Nursery vent battery
  - entity: sensor.rumpus_room_vent_battery
    name: Rumpus room vent battery
  - entity: sensor.tobins_spirit_guide_battery_level
    name: Tobins Spirit Guide battery
    charging_state:
      entity_id: binary_sensor.tobins_spirit_guide_is_charging
      state: 'on'


```

**Screenshots**
![image](https://user-images.githubusercontent.com/16028846/206308694-ac3f193c-38c2-41ff-b8db-2a1e5ed313c5.png)
![image](https://user-images.githubusercontent.com/16028846/206308755-1d70f90e-ebb1-4028-8f7a-90880bb2087b.png)

**Version**
2.1.1
2022.12.0
