### ISSUE TITLE
Possible to split state_map for value vs display

### ISSUE THREAD

**Issue by pgiblock** [maxwroc/battery-state-card#527]
**Is your feature request related to a problem? Please describe.**
Use case: a battery level reported as a binary sensor. The ones I've seen report: "normal", "low", "unavailable". In this card, "normal" seems to map to "off", and "low" maps to "on". Thus, what happens is all these switches is they show as a battery with question mark icon, and the values are "off" or "on". I can use a `state_map` to map "off" and "on" to, say, "90" and "20". This fixes the icons, but now I have these arbitrary values printed on the right. I can map "off" and "on" back to to "Normal" and "Low", which fixes the text legends, but the batteries revert back to question marks - and the sorting is wrong.  

**Describe the solution you'd like**
One way to fix this is to provide two state_maps. One for values, which will be used for sorting as well as icon levels. The other state_map will be used for labels. Thus, my solution would look something like:
```yaml
state_map:
  - from: 'off'
    to: 100
  - from: 'on'
    to: 20
label_state_map:
  - from: 'off'
    to: Normal
  - from: 'on'
    to: Low    
```
If `label_state_map` is not defined, the extension would use `state_map` for labels as well. This is the current behavior, so it shouldn't cause and regressions to users' configurations.

**Additional context**
<img width="432" alt="Screen Shot 2023-02-05 at 2 40 14 PM" src="https://user-images.githubusercontent.com/290880/216840976-167aa35e-2e42-4d3c-8d68-c665b12da6d9.png">
Note: this is a partial screenshot. "Unavailable" sorts before "Normal", then there would be "Low", then numericals. Ideally, they would be sorted: "Unavailable", "Low", numericals, "Normal".

**Comment by maxwroc** [comment]
Thanks for the suggestion. I was thinking about this already and I was planning to add a property to Convert object so it would be something like

```yaml
state_map:
  - from: off
    to: 100
    display: "Normal" 
```
