### ISSUE TITLE
Support groups created via UI/Helpers

### ISSUE THREAD

**Issue by loocd** [maxwroc/battery-state-card#529]
I just stumbled upon this card and it looks amazing. Just one little thing about the groups functionality.

**Describe what is wrong**
Using existing HA groups to populate the individual entities would be amazing, as this would spare me from adding the same entities in multiple places.
My understanding is: I add the group as the only entity and this would populate all individual devices, according to `group.switches_batteries` in this explanation: https://github.com/maxwroc/battery-state-card#battery-groups

However, the new UI groups in HomeAssistant no longer follow the `groups.*` terminology but are added as a `sensor.*`
Adding this sensor results in a single sensor being added, rather than all the containing entities.

How can I get this to work using the new UI groups from HomeAssistant?

**Card configuration**
```
type: custom:battery-state-card
sort_by_level: asc
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: sensor.hue_motion_sensor_1_battery_2
    name: Bewegungsmelder Esszimmer
  - sensor.batterien_sensoren_aktoren
```

**Screenshot**
![Unbenannt](https://user-images.githubusercontent.com/56512098/218268396-20f88c85-dbf7-41c3-bb99-dd1b6f3a0125.png)

**Version**
v2.1.1
