### ISSUE TITLE
Is it possible to exclude depending on helper value

### ISSUE THREAD

**Issue by sweede-se** [maxwroc/battery-state-card#539]
Hi,

Is it possible to exclude any sensors who's values are below a input_number helper? Have tried the code below but it doesn't work.

```
filter:
  include:
    - name: attributes.device_class
      value: battery
  exclude:
    - name: state
      value: {{ (states('input_number.batteriniva') | int() }}
      operator: '>'
```

**Comment by pinkfloydFR** [comment]
Don't know what exatly you want, or if is already solved, but simply : 

```
  exclude:
    - name: state
      value: 40
      operator: '>'
```
