### ISSUE TITLE
Secondary Info "charging" showing on all entities while just one is actually charging

### ISSUE THREAD

**Issue by SeLLeRoNe** [maxwroc/battery-state-card#54]
**Describe the bug**
I have implemented the secondary_info option to show the "Charging" text when the battery is actually charging but it is being show all all battery entities in the card even when just 1 is charging.

**How to reproduce**
Steps to reproduce the behavior.
- Set the card with multiple entities and the secondary_info: charging to each entity
- Set one battery to charge

**Expected behavior**

**YAML configuration**
```yaml
          - type: custom:battery-state-card
            color_thresholds:
              - value: "unknown"
                color: "#808080"
              - value: 20
                color: "#990000"
              - value: 40
                color: "#CC6600"
              - value: 60
                color: "#FF8000"
              - value: 80
                color: "#009900"
              - value: 100
                color: "#009933"
            entities:
              - entity: sensor.andrea_oneplus5_battery
                name: "Andrea - OnePlus 5"
                secondary_info: charging
                charging_state:
                  entity_id: sensor.andrea_oneplus5_charging
                  state: "charging"
              - entity: sensor.andrea_honor8_battery
                name: "Andrea - Honor 8"
                secondary_info: charging
                charging_state:
                  entity_id: binary_sensor.andrea_honor8_charging
                  state: "on"
              - entity: sensor.andrea_xt1032_battery
                name: "Andrea - Motorola XT1032"
                secondary_info: charging
                charging_state:
                  entity_id: input_boolean.andrea_xt1032_charging
                  state: "on"
              - entity: sensor.sonia_mi9tpro_battery
                name: "Sonia - Mi 9T Pro"
                secondary_info: charging
                charging_state:
                  entity_id: input_boolean.sonia_mi9tpro_charging
                  state: "on"
              - entity: sensor.sonia_honor8_battery
                name: "Sonia - Honor 8"
                secondary_info: charging
                charging_state:
                  entity_id: binary_sensor.sonia_honor8_charging
                  state: "on"

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9599441/82334576-74d80d00-99e8-11ea-8779-d2ccd53d0efc.png)

**Version**
What is the version of the card?
1.3.0
