### ISSUE TITLE
Duplicate entity_id

### ISSUE THREAD

**Issue by pinkfloydFR** [maxwroc/battery-state-card#547]
Hi,

All version up to date, on raspberry pi , HA OS.

Here is my configuration : 

```
type: vertical-stack
cards:
  - type: vertical-stack
    cards:
      - type: custom:button-card
        color_type: label-card
        color: rgb(238, 233, 119)
        name: Lumieres Allumées
        aspect_ratio: 15
      - type: custom:battery-state-card
        color_gradient:
          - '#ff0000'
          - '#ffff00'
          - '#00ff00'
        icon: mdi:lightbulb-outline
        bulk_rename:
          - from: ZIG_relais_
            to: ''
          - from: ZIG_LED_Denis
            to: LED Bureau Denis
          - from: Yeelight Ceiling4 0x112f9312 Ambilight
            to: Plafonnier Salle a Manger Ambilight
          - from: ZIG-
            to: ''
        sort_by_level: asc
        collapse: 4
        filter:
          include:
            - name: entity_id
              value: switch.zig_relais*
            - name: entity_id
              value: light.*
          exclude:
            - name: state
              value: 'Off'
              operator: '='
            - name: state
              value: Unavailable
              operator: '='
            - name: entity_id
              value: '*p101*'
            - name: entity_id
              value: switch.zig_relais_denis
```

And here is the result : 

![image](https://user-images.githubusercontent.com/49475899/235292441-c9fce6f6-26c6-4454-bbef-fbe19910afc1.png)

Note 1 : Without the bulk_rename block, same result ( with different name of course ) ( capture is without to show the real name )
Note 2 : Strange behaviour, the state Off in exclude work, but state On in include doesn't.

Thanks for helping !
