### ISSUE TITLE
Entities are reqired(?)

### ISSUE THREAD

**Issue by Tom-ahawk** [maxwroc/battery-state-card#55]
The card   entities are required and in addition filters with wildcard can be used.
Why not only filters?
Now I must specify at least one entity and in addition filters for making the card work. 

```
type: 'custom:battery-state-card'
title: Sensor Battery Status
sort_by_level: asc
entities:
  - entity: sensor.fib_flood_sensor1_battery_level
filter:
  include:
    - name: entity_id
      value: sensor.fib_*_battery_level
    - name: attributes.device_class
  exclude:
    - name: state
      value: 5
      operator: =
```
