### ISSUE TITLE
Possibly not showing up anymore in Home Assistant 2023.6.3 

### ISSUE THREAD

**Issue by mitchins** [maxwroc/battery-state-card#556]
Apologies if there is user error, but I've noticed there hasn't been an official release of the card in almost 18 months and it doesn't seem to work for me straight off the bat even after resetting the frontend and HAOS itself.

**Describe the bug**
The card does not appear in the lovelace list, nor does forcing it manually via manual YAML card display anything.

**How to reproduce**
Install the add-on via HACS.
Restarted both the front end (ctr-shift-r), and then restarted home-assistant itself.

**Expected behavior**
The card should show up in the list, or at least work when the example code is forced via "manual" card type YAML.

**YAML configuration (current filter based example from README.md** 
```yaml
type: custom:battery-state-card
title: Filters
sort_by_level: asc
bulk_rename:
  - from: Battery Level
    to: sensor
  - from: /\s(temperature|temp)\s/
    to: ' temp. '
entities:
  - entity: sensor.temp_outside_battery_numeric
    multiplier: 10
    name: Outside temp. sensor
filter:
  include:
    - name: entity_id
      value: '*_battery_level'
    - name: attributes.device_class
      value: battery
  exclude:
    - name: state
      value: 99
      operator: '>'

```

**Screenshots**
![image](https://github.com/maxwroc/battery-state-card/assets/1016050/d3e3e85f-4730-4c61-a406-d6eca19192cb)
![image](https://github.com/maxwroc/battery-state-card/assets/1016050/938cb18d-b77e-4dc4-a1b1-77c0879a3414)
![image](https://github.com/maxwroc/battery-state-card/assets/1016050/007742db-f51a-4c2c-b2ae-345206122c74)

**Version**
Card: V2.1.1
Home Assistant 2023.6.3 
Supervisor 2023.06.4 
Operating System 10.3 
Frontend 20230608.0 - latest

**Comment by mitchins** [comment]
Nevermind, it seems like removing 
```yaml
entities:
  - entity: sensor.temp_outside_battery_numeric
    multiplier: 10
    name: Outside temp. sensor
```

allows it to show.. weird
