### ISSUE TITLE
Card displays nothing at all

### ISSUE THREAD

**Issue by bkr1969** [maxwroc/battery-state-card#558]
**Describe the bug**
The card just stopped working totally

**How to reproduce**
Try to install the card.  Nothing will display

**Expected behavior**
The same battery info displayed that showed yesterday

**YAML configuration**
      card:
        type: custom:battery-state-card
        title: Battery Stuff
        entities:
          - entity: sensor.misc_iphone_13_battery_state
            name:  iPhone 13
            charging_state:
              attribute:
                name: battery_status
                value: Charging
            color_gradient:
              - '#ff0000'
              - '#ffff00'
              - '#289e04'

```

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Version**
2.1.1
Broke in 2023.8.2, tried updating to 8.3 without success

**Comment by bkr1969** [comment]
Even using the exact code from this repository, nothing displays:
```
type: custom:battery-state-card
title: "Charging indicators"
entities:
  - entity: sensor.device_battery_numeric
    charging_state: # uses other entity state value
      entity_id: binary_sensor.device_charging
      state: "on"
  - entity: sensor.mi_roborock
    charging_state: # uses sensor.mi_roborock state value
      state: "charging"
      icon: "mdi:flash"
      color: "yellow"
  - entity: sensor.samsung
    charging_state: # uses is_charging attribute on sensor.samsung entity
      attribute:
        name: "is_charging"
        value: "yes"
```
