### ISSUE TITLE
Rename entities or change icon when inside a collapse group

### ISSUE THREAD

**Issue by stleusc** [maxwroc/battery-state-card#560]
**Describe the bug**
I want/need to rename some entities and change the icon when they are in a collapse group.
This code in the collapse group leads to the [object Object] in the screenshot.

```
      - entity: sensor.shade_dining_room_battery
        name: Shade Dining Room
        icon: mdi:blinds
```

**How to reproduce**
Simply uses below yaml configuration.

**Expected behavior**
Ability to change icon and rename entities in collapse groups.

**YAML configuration**
```yaml

type: custom:battery-state-card
title: Battery Levels
sort_by_level: asc
collapse:
  - name: 'Thermostats (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    icon: mdi:air-conditioner
    entities:
      - sensor.sensi_upstairs_battery
      - sensor.sensi_basement_battery
      - sensor.sensi_cooling_battery
      - sensor.sensi_first_floor_battery
      - entity: sensor.shade_dining_room_battery
        name: Shade Dining Room
        icon: mdi:blinds
entities:
  - entity: sensor.shade_dining_room_battery
    name: Shade Dining Room
    icon: mdi:blinds
  - sensor.scene_switch_battery
  - entity: sensor.water_sensor_battery
    name: Water Sensor
    icon: mdi:water-alert

```

**Screenshots**

![image](https://github.com/maxwroc/battery-state-card/assets/1132106/82800301-8acc-4488-8422-87a64e076076)

**Version**

V2.1.1
latest HA

**Comment by maxwroc** [comment]
This is not a bug. It is by design. Entities list in the group object accepts only strings.

When you leave the entity_id there and remove all of the other properties everything should work. You specify the entity details/configuration on the main `entities` list - as you have done already. Here is the fixed config:
```yaml
type: custom:battery-state-card
title: Battery Levels
sort_by_level: asc
collapse:
  - name: 'Thermostats (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    icon: mdi:air-conditioner
    entities:
      - sensor.sensi_upstairs_battery
      - sensor.sensi_basement_battery
      - sensor.sensi_cooling_battery
      - sensor.sensi_first_floor_battery
      - sensor.shade_dining_room_battery
entities:
  - entity: sensor.shade_dining_room_battery
    name: Shade Dining Room
    icon: mdi:blinds
  - sensor.scene_switch_battery
  - entity: sensor.water_sensor_battery
    name: Water Sensor
    icon: mdi:water-alert
```
