### ISSUE TITLE
tap_action stopped working

### ISSUE THREAD

**Issue by 03397** [maxwroc/battery-state-card#57]
**Describe the bug**
The tap_action stopped working in one of the last 2-3 upgrades. I have pinpointed this at the latest version. 

**How to reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**YAML configuration**
```yaml
# please paste here your card config
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: sensor.aeotec_zw129_wallmote_duo_battery_level_2
  - entity: sensor.aeotec_zw129_wallmote_duo_battery_level_3
  - entity: sensor.aeon_labs_zw130_wallmote_quad_battery_level
  - entity: sensor.aeotec_zwa003_nanomote_quad_battery_level
name: Recharchable Batteries
tap_action:
  action: more-info
type: 'custom:battery-state-card'
```

**Screenshots**
When I click I am getting this error message
https://xxxx.xxxxx.xxxx.xxx:yyyyy/hacsfiles/battery-state-card/battery-state-card.js:37:939 Uncaught TypeError: t.card.dispatchEvent is not a function

**Version**
What is the version of the card?
1.3.2
