### ISSUE TITLE
Sort by state seems to not work

### ISSUE THREAD

**Issue by Bubbgump209** [maxwroc/battery-state-card#589]
**Describe the bug**
The sort by state seems to have no effect. 

**How to reproduce**
Using the default card config:
```
type: custom:battery-state-card
secondary_info: "{last_changed}"
filter:
  include:
    - name: "attributes.device_class"
      value: "battery"
sort:
  by: "state"
collapse: 8
bulk_rename:
  - from: " Battery"
  - from: " level"
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
```

**Expected behavior**
By default entities would sort by charge percent. Additionally desc "true" or " false" would order the entities either ascending or descending based on their charge percent.

**YAML configuration**

```
type: custom:battery-state-card
secondary_info: "{last_changed}"
filter:
  include:
    - name: "attributes.device_class"
      value: "battery"
sort:
  by: "state"
  desc: "false"
collapse: 8
bulk_rename:
  - from: " Battery"
  - from: " level"
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
```

vs 

```
type: custom:battery-state-card
secondary_info: "{last_changed}"
filter:
  include:
    - name: "attributes.device_class"
      value: "battery"
sort:
  by: "state"
  desc: "true"
collapse: 8
bulk_rename:
  - from: " Battery"
  - from: " level"
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
```

# please paste here your card config

See above

**Screenshots**

<img width="487" alt="Screenshot 2023-10-25 at 1 54 12 PM" src="https://github.com/maxwroc/battery-state-card/assets/59414539/439ada7a-a050-4129-ad58-d5b23acf2165">

**Version**
Card version 2.1.1
HA version 2023.10.5
