### ISSUE TITLE
v3.0.0 sort/color doesn't work?

### ISSUE THREAD

**Issue by RedNo7** [maxwroc/battery-state-card#594]
**Describe the bug**
I have set `sort' to both "name" and "state, but always seem to get a random sort
I am, using the color per the instructions, but also getting no gradient

**How to reproduce**
use my config below

**Expected behavior**
The list should be sorted by name and be using the gradient color scheme (using config below)

**YAML configuration**
```yaml
- type: custom:battery-state-card
  title: "Motion sensors"
  sort:
    by: "name"
  colors:
    steps:
      - "#ff0000" # red
      - "#ffff00" # yellow
      - "#00ff00" # green
    gradient: true
  bulk_rename:  # note: "to" is not required if you want to remove string
    - from: " motion Battery"
  filter:
    include: 
      - name: entity_id
        value: "sensor.*_sensor_battery"
      - name: entity_id
        value: "sensor.*_motion_battery"
```

**Screenshots**
![Screenshot 2023-11-04 at 09 55 12](https://github.com/maxwroc/battery-state-card/assets/130979051/0598056b-ee85-4c37-9064-aa52c54a31fe)

**Version**
3.0.0

**Comment by RedNo7** [comment]
I should add, I also tried this (using the default config):
```yaml
- type: custom:battery-state-card
  title: "Motion sensors"
  bulk_rename:  # note: "to" is not required if you want to remove string
    - from: " motion Battery"
  filter:
    include: 
      - name: entity_id
        value: "sensor.*_sensor_battery"
      - name: entity_id
        value: "sensor.*_motion_battery"

```

**Comment by maxwroc** [comment]
Please open developer tools in your browser (Win Chrome - F12) and please tell me what version do you see for the card:
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/633c6468-9886-49b4-b5da-96ff8a3a9c49)

**Comment by RedNo7** [comment]
3.0.0
![Screenshot 2023-11-04 at 11 26 02](https://github.com/maxwroc/battery-state-card/assets/130979051/3606a020-d743-4e6b-bab7-b1d4082c71e9)

**Comment by maxwroc** [comment]
I don't have a repro unfortunately on Win/Chrome, Win/Edge, iOS/Safari, iOS/Chrome nor Android/Chrome. 

Can you please confirm that there are no errors in the console related to the card (below the place where the version is printed)

I'll keep this issue open for now - just in case someone else experiences something similar.

**Comment by RedNo7** [comment]
Hi,

I can confirm no errors for `battery-state-card`.
![Screenshot 2023-11-04 at 12 12 33](https://github.com/maxwroc/battery-state-card/assets/130979051/43ec8016-0393-46e0-ac0f-0d648abacdcc)

**Comment by RedNo7** [comment]
OK, got it working!

This is what I did (to help others):
| Viewer | sequence |
| :- | :- |
| Safari | **_delete_** `battery-state-card` ➜ **_restart_** HA ➜ **_install_** `battery-state-card` ➜ **_restart_** HA |
Companion app | **_App Configuration_** ➜ **_Debugging_** ➜ **_Reset frontend cache_** |

**However**  `sort`, `colours` & `bulk_rename` **need to be explicitly written in the config** even though the docs say this is the default:
```yaml
sort:
  by: "name"
colors:
  steps:
    - "#ff0000" # red
    - "#ffff00" # yellow
    - "#00ff00" # green
  gradient: true
bulk_rename:  # note: "to" is not required if you want to remove string
  - from: " motion Battery"
```

**Comment by RedNo7** [comment]
OK, got it working!

This is what I did (to help others):
| Viewer | sequence |
| :- | :- |
| Safari | **_delete_** `battery-state-card` ➜ **_restart_** HA ➜ **_install_** `battery-state-card` ➜ **_restart_** HA |
Companion app | **_App Configuration_** ➜ **_Debugging_** ➜ **_Reset frontend cache_** |

**However**  `sort`, `colours` & `bulk_rename` **need to be explicitly written in the config** even though the docs say this is the default:
```yaml
sort:
  by: "name"
colors:
  steps:
    - "#ff0000" # red
    - "#ffff00" # yellow
    - "#00ff00" # green
  gradient: true
bulk_rename:  # note: "to" is not required if you want to remove string
  - from: " motion Battery"
```
