### ISSUE TITLE
Icon alligment different than on entities card

### ISSUE THREAD

**Issue by bieniu** [maxwroc/battery-state-card#60]
**Describe the bug**
The entities on the `battery-state-card` are alignment differently than on the `entities` card.

**Expected behavior**
The alignment of the icons should be the same as on the `entities` card.

**YAML configuration**
```yaml
     - type: custom:battery-state-card
        name: "Baterie sensorów ruchu"
        tap_action:
          action: more-info
        color_thresholds:
          - value: 20
            color: var(--label-badge-red)
          - value: 40
            color: var(--label-badge-yellow)
          - value: 100
            color: var(--state-icon-color)
        entities:
          - sensor.battery_motion_sensor_przedpokoj
          - sensor.battery_motion_sensor_salon_1
          - sensor.battery_motion_sensor_salon_2
          - sensor.battery_motion_sensor_pracownia
          - sensor.battery_motion_sensor_goscinny
          - sensor.battery_motion_sensor_schody
          - sensor.battery_motion_sensor_antresola
          - sensor.battery_motion_sensor_gabinet
          - sensor.battery_motion_sensor_antek
          - sensor.battery_motion_sensor_sypialnia
```

**Screenshots**
![battery](https://user-images.githubusercontent.com/478555/82500470-b6091380-9af3-11ea-8f02-a1830a9346e6.png)

**Version**
1.3.2
