### ISSUE TITLE
Combining Color Gradient & Charging Status

### ISSUE THREAD

**Issue by JAudi23** [maxwroc/battery-state-card#603]
**Describe what is wrong**
I just started playing with this today, and have successfully used the color gradient card, and then I was able to add the sort option.
I tried to also include the charging_state code, however the card does not seem to recognize it.
Is this possible, or is my code incorrect somewhere?

**YAML configuration**
```yaml

type: custom:battery-state-card
title: Device Battery Levels
sort: state
charging_state:
  attribute:
    - name: Battery State
      value: Charging
    - name: is_charging
      value: true
  state:
    - charging
    - Charging
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
entities:
  - entity: sensor.front_door_battery
    name: Front Door Lock
  - entity: sensor.interior_garage_door_battery
    name: Interior Garage Door Lock
  - entity: sensor.roomba_battery
    name: Roomba Vacuum
  - entity: sensor.nest_temperature_sensor_daughter_s_bedroom_battery_level
    name: Daughter's Room Temperature Sensor
  - entity: sensor.nest_temperature_sensor_son_s_bedroom_battery_level
    name: Son's Room Temperature Sensor
  - entity: sensor.nest_temperature_sensor_master_bedroom_battery_level
    name: Master Bedroom Temperature Sensor
  - entity: sensor.water_level_sensor_battery_level
    name: Sump Pit Water Level Sensor
  - entity: device_tracker.daughter
    name: Daughter's iPhone
  - entity: device_tracker.son
    name: Son's iPhone
  - entity: device_tracker.spouse
    name: Spouse's iPhone
  - entity: device_tracker.mine
    name: My Samsung Galaxy S22 Ultra
```

**Screenshot**

![image](https://github.com/maxwroc/battery-state-card/assets/107599616/9770e003-e1db-43a2-ae22-b63b5d377a23)

**Version**

v3.0.1
