### ISSUE TITLE
Relative time processing error

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#617]
**Describe the bug**

![image](https://github.com/maxwroc/battery-state-card/assets/8268674/6565165b-2b04-4516-b526-7ade6f6ac214)

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

type: custom:battery-state-card
secondary_info: '{last_changed}'
filter:
  include:
    - name: attributes.device_class
      value: signal_strength

```

**Screenshots**

**Version**
