### ISSUE TITLE
Filter "not_exists" / "missing" operator

### ISSUE THREAD

**Issue by maxwroc** [maxwroc/battery-state-card#618]
**Is your feature request related to a problem? Please describe.**

I want to exclude entities without specific attribute

**Describe the solution you'd like**

```yaml
filter:
  include: # filters for auto-adding
    - name: entity_id # entities which id ends with "_battery_level"
      value: "device_tracker.*"
  exclude
    - name: attributes.rssi
      operator: not_exists
```
