### ISSUE TITLE
Card not shown at all after updating to 3.1.0

### ISSUE THREAD

**Issue by bcutter** [maxwroc/battery-state-card#623]
**Describe the bug**

After updating from 3.0.1 to 3.1.0, the card is not shown at all.

**How to reproduce**
Update from 3.0.1 to 3.1.0.

**Expected behavior**
Card is shown as there are no breaking changes listed at https://github.com/maxwroc/battery-state-card/releases/tag/v3.1.0

**YAML configuration**
Just one example
```
- type: custom:battery-state-card
    entities:
      - entity: group.batterystate_devices
    title: 📱 Geräte
    secondary_info: '{last_updated}'
    tap_action: more-info
    sort:
      by: state
      desc: false
    collapse: 12
    filter: 0
    round: 0
    unit: '%'
    colors: null
    bulk_rename:
      - from: ' Battery Level'
        to: ''
      - from: ' Battery level'
        to: ''
      - from: ' Akkufüllstand'
        to: ''
      - from: ' Batterieladung'
        to: ''
      - from: ' Batteriestand'
        to: ''
```

**Screenshots**
Just imagine a white/empty space here...

**Version**
Battery State Card: 3.1.0
HA: 2023.4.6

**Comment by maxwroc** [comment]
can you please check if there are any errors in the dev console in your browser

**Comment by 7oku** [comment]
Same issue here. Cache cleared. Console shows missing files:

```
XHRGET
https://raw.githubusercontent.com/maxwroc/battery-state-card/v3.1.0/node_modules/tslib/tslib.es6.js
[HTTP/2 404  158ms]

XHRGET
https://<redacted>/unknown/src/reactive-element.ts
[HTTP/1.1 404  0ms]

XHRGET
https://<redacted>/unknown/src/lit-element.ts
[HTTP/1.1 404  0ms]

XHRGET
https://<redacted>/unknown/src/lit-html.ts
[HTTP/1.1 404  0ms]

XHRGET
https://<redacted>/unknown/src/scoped-custom-element-registry.js
[HTTP/1.1 404  0ms]
```

Not sure if the last 4 belong to battery state card.

**Comment by maxwroc** [comment]
The files from https://raw.githubusercontent.com/maxwroc/battery-state-card/* are being downloaded only when the console is open (they are referenced in the .js.map file which is included in the release package - it is useful if you want to debug js locally). But this is not used by the browser to execute sth on the HA page. The actual file which is being loaded on the page is battery-state-card.js and this one doesn't have references to such files like "tslib" etc

![image](https://github.com/maxwroc/battery-state-card/assets/8268674/b6918b7c-8782-4b7b-a54e-f6b23ee54f29)

I was curious if there are some js errors?

I assume that if you downgrade everything works again?

**Comment by maxwroc** [comment]
Let's check how many people will report this problem. TBH the same/similar issues are being reported after every single recent release and it is usually a problem on the side of the user.

I need more info to investigate it further. If you can try to play with the config and notice a pattern that when you add/remove something the card shows up it would be really helpful. You can start from something basic like:
 ```yaml
type: custom:battery-state-card
entities:
  - sensor.your_battery_entity_which_worked_before
```
And later add other parts of your current config to this one (one by one) checking if card renders

**Comment by bcutter** [comment]
Well I did so and built from

```
type: custom:battery-state-card
entities:
 - sensor.your_battery_entity_which_worked_before
```

to

```
  - type: custom:battery-state-card
    entities:
     - sensor.non-existing-entity
    title: '*** Test BSC v3.1.0 ***'
    secondary_info: '{last_updated}'
    tap_action: more-info
    sort:
      by: state
      desc: false
    collapse: 12
    filter: 0
    round: 0
    unit: '%'
    colors: null
    bulk_rename:
      - from: ' Battery Level'
        to: ''
      - from: ' Battery level'
        to: ''
      - from: ' Akkufüllstand'
        to: ''
      - from: ' Batterieladung'
        to: ''
      - from: ' Batteriestand'
        to: ''
```

**What I discovered in 1/2 an hour of further testing:**
- even the minimal (basic) version fails to render completely, ONCE an actually existing entity is referenced
- as long as a non-existing one is given, the card seems to render just fine:
![grafik](https://github.com/maxwroc/battery-state-card/assets/13799156/6cffce0a-2002-4d27-8931-40bef7d436fb)
- update: 
```
  - type: custom:battery-state-card
    entities:
     - sensor.non-existing-entity
     - sensor.home_assistant_core_cpu_percent
     #- sensor.iphone_battery_level
```
renders fine too:
![grafik](https://github.com/maxwroc/battery-state-card/assets/13799156/04dad155-4823-4487-9d8d-e175be494c84)
- but using my `group.batterystate_devices` as entity does not. So does when using one random entity of that group like `sensor.iphone_battery_level`, which gives <nothing> again
- I compared the working entity `sensor.home_assistant_core_cpu_percent` to (one of) the non-working `sensor.iphone_battery_level`:
![grafik](https://github.com/maxwroc/battery-state-card/assets/13799156/70340e6d-adcb-48ff-98d5-1565b996dfee)
![grafik](https://github.com/maxwroc/battery-state-card/assets/13799156/fd253126-212b-4315-84bc-b6bab352aeca)
So in this comparison the only difference are `device_class` and `state_class`

So it seems like if there's only one single "wrong" entity, v3.1.0 is refusing to render the whole card. Just a wild theory.

Really not sure if you can make something out of this. Trying with many different entities is likely a good approach to find a pattern. As I'm not used to the dev-tools power of my browser I'd need to have an exact how-to if you want me to test something (using Firefox). By the way of course I tested it with other browsers too: the HA Companion app (iOS) also shows not a single card anymore with 3.1.0. I'll downgrade for now...

**Comment by maxwroc** [comment]
Thank you so much for such detailed testing and info. I'll try to figure out something from it in the next couple of days (although I'll be traveling and I don't know how much time I'll be able to spend on it). 

What I can recommend at the moment only is to downgrade to 3.0.X 😞

**Comment by 7oku** [comment]
Yes, solved this as well for me. My pretty simple config was: 

```
type: custom:battery-state-card
title: Filters
sort_by_level: asc
entities: null
state_map:
  - from: 'off'
    to: OK
filter:
  include:
    - name: entity_id
      value: '*_batter*'
```

I had to remove the `entities: null` line. Not sure by what this line was introduced. Only changes recently where clicking through the updates of HA and addons.

**Comment by bcutter** [comment]
> Thank you so much for such detailed testing and info. I'll try to figure out something from it in the next couple of days (although I'll be traveling and I don't know how much time I'll be able to spend on it).
> 
> What I can recommend at the moment only is to downgrade to 3.0.X 😞

I referenced two other issues with similar problem descriptions. So fix one problem, solve several issues... :-)

**Comment by maxwroc** [comment]
Thanks! Unfortunately Mon will be the earliest I'll be able to look into it. The only advice I can give now is to downgrade, sorry for the inconvenience

**Comment by maxwroc** [comment]
@bcutter why do you have filter set to 0? I bet this is causing the problem in your case
![image](https://github.com/maxwroc/battery-state-card/assets/8268674/49e74a0e-0fe5-4d03-88c6-66217cb277fc)

I think all referenced other issues are not related - in all of them the card broke in v3.1.1 and v3.1.0 was working fine

**Comment by dnedeltchev** [comment]
Upgraded to 3.1.2 but the problem is still there. As mentioned in https://github.com/maxwroc/battery-state-card/issues/630
removing the sort section fixes the display issue, i.e. entities are visible, however they are not sorted. 3.1.0 still works as expected.

**Comment by Phoenix-DH** [comment]
> Upgraded to 3.1.2 but the problem is still there. As mentioned in #630 removing the sort section fixes the display issue, i.e. entities are visible, however they are not sorted. 3.1.0 still works as expected.

I have exactly the same issue here.

**Comment by maxwroc** [comment]
@dnedeltchev First of all let's not mix two/three things. This issue was reported after the upgrade to v3.1.0. You are saying that this is the version which works for you. The OP's problem in #630 most probably will be fixed in 3.1.1 as indeed there was a bug in filters introduced.

The sort issue which you are experiencing is probably a separate third problem. Unfortunately I still don't know what can be the root cause.

**Comment by Phoenix-DH** [comment]
Ah, I did not get taht, just read this one here.

**Comment by dnedeltchev** [comment]
> @dnedeltchev First of all let's not mix two/three things. This issue was reported after the upgrade to v3.1.0. You are saying that this is the version which works for you. The OP's problem in #630 most probably will be fixed in 3.1.1 as indeed there was a bug in filters introduced.
> 
> The sort issue which you are experiencing is probably a separate third problem. Unfortunately I still don't know what can be the root cause.

Hi Max,

In which case, https://github.com/maxwroc/battery-state-card/issues/630, should not be marked as duplicate of this one and should not be closed as completed. I'd suggest you reopen https://github.com/maxwroc/battery-state-card/issues/630.

**Comment by dnedeltchev** [comment]
Just to add, https://github.com/maxwroc/battery-state-card/issues/630, was logged by me and the problem is not fixed in 3.1.1 or 3.1.2.
3.1.0 works as expected including the sorting. So I'm staying on 3.1.0 for now.

**Comment by maxwroc** [comment]
Oh ok, I didn't realize that it was you who reported this (and I didn't check it before replying here :) ). Let's continue the discussion about your problem there

**Comment by bcutter** [comment]
> @bcutter why do you have filter set to 0? I bet this is causing the problem in your case ![image](https://private-user-images.githubusercontent.com/8268674/294818362-49e74a0e-0fe5-4d03-88c6-66217cb277fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDQ2MTQsIm5iZiI6MTcwNDc0NDMxNCwicGF0aCI6Ii84MjY4Njc0LzI5NDgxODM2Mi00OWU3NGEwZS0wZmU1LTRkMDMtODhjNi02NjIxN2NiMjc3ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMjAwNTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg0ZDk4ODhmODVjNDY4NjhiOWNmNWU3YjU5MmI3ODlhNmE0NGM0MGQ4MWU5ZWY5NWI0NmRmY2JjYTE1MjVmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.91zKXcEqWm5QbWqb2SXzlkI7rTkfxTFHsK1ptiH5Nl4)
> 
> I think all referenced other issues are not related - in all of them the card broke in v3.1.1 and v3.1.0 was working fine

No unfortunately your bet is wrong. Tested it once again (had it there cause on some places I use the filter, on others I use specific entities).

I think you could read this post https://github.com/maxwroc/battery-state-card/issues/623#issuecomment-1872630443 once again where I tested by building up step by step from a minimal version. Filter is irrelevant here.

(note: I tested with 3.1.0 and 3.1.2, no difference - still only empty cards!)

**Comment by maxwroc** [comment]
Thanks. I will go through this one more time. There were quite "few" changes in v3.1.0 - I need to think about beta releases - it will be easier to find the culprit

**Comment by CH1PSET1** [comment]
My card is not displayed, starting from version 1.3.1 with value = battery, without it the data appears
              filter:
                include:
                  - name: "attributes.device_class"
                    **value: "battery"**

Tell me how to roll back to 1.3.0?

**Comment by bcutter** [comment]
> value = battery, without it the data appears

Interesting. That might match with what I tested back in https://github.com/maxwroc/battery-state-card/issues/623#issuecomment-1872630443. Card was shown fine until I added (via include or entities) entities with battery values.

---

Rolling back is easy if you installed using HACS. Select the frontend integration, re-download and select the older version. Reset frontend cache, done.

**Comment by bcutter** [comment]
Please note: tested https://github.com/maxwroc/battery-state-card/releases/tag/v3.1.3, no change (cards still not shown at all).

**Comment by chma73** [comment]
I have the same issue
![1](https://github.com/maxwroc/battery-state-card/assets/137674516/c0df3cd1-1239-419d-b219-f36e9522a43c)

**Comment by hrw** [comment]
For me it was not working in 3.1.[01] but started working again in 3.1.[23].

```yaml
type: custom:battery-state-card
title: Stan baterii
filter:
  include:
    - name: attributes.device_class
      value: battery
sort:
  by: state
bulk_rename:
  - from: ' Bateria'
  - from: ' Battery'
  - from: ' level'
colors:
  steps:
    - '#ff0000'
    - '#ff9800'
    - '#4caf50'
  gradient: true
```
