### ISSUE TITLE
Entities are not showing when sort option is present in the config

### ISSUE THREAD

**Issue by dnedeltchev** [maxwroc/battery-state-card#630]
Upgraded to latest version 3.1.1 and something broke, my card was showing only 2 entries. Reverting to 3.1.0 all works as expected. 

**Describe the bug**

**How to reproduce**
Upgrade to 3.1.1.

**Expected behavior**

**YAML configuration**
type: custom:battery-state-card
title: Battery levels (<70%)
tap_action: more-info
secondary_info: '{last_changed}'
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
sort:
  by: state
filter:
  exclude:
    - name: state
      value: 70
      operator: '>'
    - name: entity_id
      value: sensor.front_door_battery
    - name: entity_id
      value: binary_sensor.living_room_motion_sensor_1_battery_low
  include:
    - name: attributes.device_class
      value: battery
collapse: 6
entities:
  - entity: sensor.xxx_s_iphone_battery_level
    name: xxx's phone

# please paste here your card config

```

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->

**Version**
<!-- What is the version of the card? -->
<!-- If regression happened after updating Home assistant please add HA version as well. -->

**Comment by kineticscreen** [comment]
Just updated and now my card shows no entities, instead of loads:

`type: custom:battery-state-card
title: Batteries
secondary_info: '{last_changed}'
filter:
  include:
    - name: attributes.device_class
      value: battery
sort:
  by: state
collapse: 8
bulk_rename:
  - from: ' Battery'
  - from: ' level'
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
`

**Comment by tyacko2** [comment]
Sort seems to be the issue here.  Once I removed sort from mine everything showed up again.

I tried...
sort: state

I even tried...
sort:
  by: state

In both cases, none of the batteries will display.  As soon as I remove sort everything appears again.  So, I'm suspecting this is a code defect in the sort code.

**Comment by dnedeltchev** [comment]
> Sort seems to be the issue here. Once I removed sort from mine everything showed up again.
> 
> I tried... sort: state
> 
> I even tried... sort: by: state
> 
> In both cases, none of the batteries will display. As soon as I remove sort everything appears again. So, I'm suspecting this is a code defect in the sort code.

Yep, I can confirm that removing sort fixes the issue. I'll wait for a fix (the next release) before upgrading.

**Comment by kineticscreen** [comment]
This fix isn't actually working for me. Even removing sort doesn't make the card appear.

It seems like

```
filter:
  include:
    - name: attributes.device_class
      value: battery
```
doesn't seem to be generating entities anymore. If I manually add entities then they show up.

**Comment by KitHubek** [comment]
the same here. 

remove

```
sort:
  by: state
```

for now solve problem, but list isnt sorted 📦 waiting for fix

**Comment by bcutter** [comment]
Duplicate of https://github.com/maxwroc/battery-state-card/issues/623 (same root cause / core issue)

**Comment by KitHubek** [comment]
ver. 3.1.2 not solved problem. Still exsist

**Comment by maxwroc** [comment]
Can you please tell me what is your lang set in HA and how the decimals are being formatted - curious whether comma or dot is being used to separate decimal values: e.g.

98.5  vs.  98,5

I assume the problem happens when comma is used. Please let me know if I'm correct.

The additional thing which I'd like you to try is to use the following in your config (card level)
```yaml
default_state_formatting: false
```

I think this will mitigate the issue

**Comment by dnedeltchev** [comment]
Hi Max,
It's GB, I'm in the UK so it's 98.5. Let me try using default_state_formatting: false and I'll come back shortly.

**Comment by dnedeltchev** [comment]
That didn't help. Here is where I added the config.
type: custom:battery-state-card
secondary_info: '{last_changed}'
title: Battery levels
default_state_formatting: false
tap_action: more-info
....

**Comment by maxwroc** [comment]
Weird. Are there any errors in the browser dev console?

**Comment by audun-v** [comment]
I have the same problem.
I have both entities and filter to add all the entities I want. Like this.

If I remove the entities part the sort function is working.
If I remove the filter part , and only have the entities part, the sort function is also working.
If both used together the sort function is not working, and nothing is shown.

```
entities:
  - entity: vacuum.audun
  - entity: sensor.audun_sin_iphone_battery_level_2
    charging_state:
      entity_id: sensor.audun_sin_iphone_battery_state_2
      state: Charging
  - entity: sensor.edwin_sin_iphone_battery_level
    charging_state:
      entity_id: sensor.edwin_sin_iphone_battery_state
      state: Charging
filter:
  include:
    - name: entity_id
      value: sensor.sensor*_battery*
      state: charging
    - name: entity_id
      value: sensor.*_battery*
      state: charging
    - name: entity_id
      value: sensor.*_batteri*
      state: charging
    - name: entity_id
      value: sensor.battery
      state: charging
  exclude:
    - name: entity_id
      value: sensor.*iphone_battery_state*
    - name: entity_id
      value: sensor.*mobil_battery_state*
    - name: entity_id
      value: sensor.ringeklokke_battery_temperature
```
