### ISSUE TITLE
Batterie level Aarlo Camera

### ISSUE THREAD

**Issue by feron81** [maxwroc/battery-state-card#632]
I have a entity called camera.aarlo_dachterrasse. This is a outdoor camera. Now I would like to show the battery level of this device. It has a lot of under attribute. I need the under attribute "battery_level".

I tried now several things for example: 
- entity: camera.aarlo_dachterrasse

It show me nothing. Do you have an idea, how I have to set the entry for this device. For all other Battery level I have no problem.

Thank you for your help

**Comment by maxwroc** [comment]
Try the following:

```yaml
entities:
  - entity: camera.aarlo_dachterrasse
    attribute: "battery_level"
```
