### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by Phoenix-DH** [maxwroc/battery-state-card#636]
Hey together,

I am using the latest version of the card, but I did not get it managed to exclude an entry:

```
              filter:
                include:
                  - name: "attributes.device_class"
                    value: "battery"
                exlude:
                  - name: entity_id
                    value: sensor.s10x_state_of_charge
```

This is how I am trying to do it.

What am I doing wrong?

Thanks.
