### ISSUE TITLE
[BUG] state_map not working, not replace the state

### ISSUE THREAD

**Issue by wes1993** [maxwroc/battery-state-card#638]
**Describe the bug**
The state_map for sensor.portablindata_low_battery is false but in the card not replace the state

**How to reproduce**
Just configure the state_map for sensor

**Expected behavior**
Percentage value specified instead of the state

**YAML configuration**
```
type: custom:battery-state-card
sort: state
round: 0
collapse:
  - name: 'Sensori Allarme (Min: {min}%, Tot: {count})'
    secondary_info: Range Batterie {range}%
    icon: mdi:security
    group_id: sensor.batterie_allarme
  - name: 'Pulsanti (Min: {min}%, Tot: {count})'
    group_id: sensor.batterie_pulsanti
    secondary_info: Range Batterie {range}%
    icon: mdi:battery-high
  - name: 'Sensori Allagamento (Min: {min}%, Tot: {count})'
    group_id: sensor.batterie_sensori_allagamento
    secondary_info: Range Batterie {range}%
    icon: mdi:water-plus-outline
entities:
  - entity: sensor.portablindata_low_battery
    name: Porta Blindata
    state_map:
      - from: false
        to: 100
      - from: true
        to: 25
```

**Dev console errors**

[battery-state-card] Missing option for 'false' in 'state_map.'
**Screenshots**
![image](https://github.com/maxwroc/battery-state-card/assets/52070589/ac128d15-f63b-4cec-8e87-c1aa8dad9dcd)

More Details:
```
<template TemplateState(<state sensor.portablindata_low_battery=false; icon=mdi:battery, friendly_name=Batteria Scarica Porta Blindata @ 2024-01-08T12:25:12.188358+01:00>)>
```

**Version**
 v3.1.2
