### ISSUE TITLE
Regresion bug with empty card since 3.1.1 - sorting

### ISSUE THREAD

**Issue by dzikus** [maxwroc/battery-state-card#639]
**Describe the bug**

Since version 3.1.1 card stoped working - blank page.

**How to reproduce**

Use card with such config and version 3.1.1 or 3.1.2:
![image](https://github.com/maxwroc/battery-state-card/assets/3209066/6f47d65b-6877-4954-acd2-bd0dd3d647c7)

**Expected behavior**

![image](https://github.com/maxwroc/battery-state-card/assets/3209066/5b3947e4-8ee7-4b5e-99e5-6ebe10dfc448)

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Poziomy baterii
secondary_info: '{last_changed}'
filter:
  include:
    - name: attributes.device_class
      value: battery
sort:
  by: state
bulk_rename:
  - from: ' Bateria'
  - from: ' Battery'
  - from: ' Level'
atribute: battery_low, battery_level, battery
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
```

**Dev console errors**

With version 3.1.0 there are no errors at all, with 3.1.1 or 3.1.2 there is problem with sorting
![image](https://github.com/maxwroc/battery-state-card/assets/3209066/fe391746-66db-4387-801c-912bc493daff)

**Screenshots**

**Version**

3.1.1 and 3.1.2 doesn't work, 3.1.0 is last working version

Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
User interface 20240104.0
