### ISSUE TITLE
Icons show question mark and no colour

### ISSUE THREAD

**Issue by B0ndo2** [maxwroc/battery-state-card#657]
Icons show question mark and no colour

**Expected behavior**
The icons should have colours based on battery level

**YAML configuration**
```yaml

type: custom:auto-entities
card:
  type: custom:battery-state-card
  title: Batteries
  sort_by_level: asc
  collapse: 5
  tap_action: more-info
  color_thresholds:
    - value: 10
      color: '#ff0000'
    - value: 50
      color: '#fa9e0a'
    - value: 100
      color: '#00ff00'
filter:
  include:
    - entity_id: sensor.*_battery
sort:
  method: state
  numeric: false
  ignore_case: true
  reverse: true
  ip: false


```
![image](https://github.com/maxwroc/battery-state-card/assets/75389943/8446914a-f876-47b6-8e1d-c48d0f09c3ca)

**Version**
3.1.5
