### ISSUE TITLE
Adding Name to Entity in Collapsible Group

### ISSUE THREAD

**Issue by burgoyne** [maxwroc/battery-state-card#662]
I currently have a collapsible group that's working as expected, but I am wondering how I can go about changing the name displayed for each sensor? Something like:

````
collapse:
  - name: 'CR2032 (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    icon: mdi:leak
    entities:
      - entity: sensor.sensor_frontdoor_battery
        name: Front Door Contact
````
I currently display my entities like:
````
entities:
      - sensor.sensor_frontdoor_battery
````
From what I can tell from the docs, adding the `name:` option below an entity can only be done when the entity is prefixed with `- entity:`, but inside of a collapsible group it doesn't seem like that is an option.

**Version**
v3.1.5
