### ISSUE TITLE
Custom card theme config

### ISSUE THREAD

**Issue by rigrig** [maxwroc/battery-state-card#670]
**Is your feature request related to a problem? Please describe.**

I've got a "Battery Warning" card for my front page, and I'd like to apply a [custom theme](https://github.com/houtknots/UglyChristmas-Theme) to it, so it stands out when there is a problem.

**Describe the solution you'd like**

A `theme: <string>` config for the card: Override the used theme for this card with any loaded theme, same as for [built-in cards](https://www.home-assistant.io/dashboards/entities/#theme).

**Additional context**

My current setup, using [custom:auto-entities](https://github.com/thomasloven/lovelace-auto-entities) with an `entities` card and `theme: uglychristmas`:   
<details><summary>card YAML</summary>

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Battery Warning
  secondary_info: '{attributes.battery_type_and_quantity}'
  theme: uglychristmas
filter:
  include:
    - entity_id: '*_battery'
  exclude:
    - state: '> 25'
    - state: unavailable
```

</details>   

![image](https://github.com/maxwroc/battery-state-card/assets/2941436/f9a13cc0-7d13-45d1-ab5f-455634616bf4)   
Using `battery-state-card` would mean no need for the `auto-entities` wrapper, and being able to show the battery type attribute, so I know what to replace.
