### ISSUE TITLE
Lost icons and sorting after upgrading to 2024.2.1

### ISSUE THREAD

**Issue by saucepwn** [maxwroc/battery-state-card#673]
**Describe the bug**
After upgrading to 2024.2.1, I lost custom icons, icon colors, and sorting from battery-state-card. This worked prior to the update.

**How to reproduce**
Have a functioning battery-state-card with color gradients and sorting by state enabled. Upgrade from Home Assistant 2024.1.* to 2024.2.*, notice the missing icons, no color gradient, and inability to sort by battery state.

**Expected behavior**
Expect icon colors to reflect battery state, icon glyph to reflect the battery state, and sorting by battery state.

**YAML configuration**
```yaml
type: custom:battery-state-card
filter:
  include:
    - name: attributes.device_class
      value: battery
  exclude:
    - name: entity_id
      value: binary_sensor.*
    - name: entity_id
      value: '*mac*'
    - name: entity_id
      value: '*s22*'
sort:
  by: state
bulk_rename:
  - from: ' Battery'
  - from: ' level'
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true

```

**Dev console errors**
No console errors

**Screenshots**
<img width="531" alt="Screenshot 2024-02-09 at 10 05 33" src="https://github.com/maxwroc/battery-state-card/assets/5727738/a0f846f6-918c-4774-b15c-6e55ec34552a">

**Version**
BATTERY-STATE-CARD  3.1.5
Home Assistant: 2024.2.1
