### ISSUE TITLE
Exclude does not always work

### ISSUE THREAD

**Issue by RedNo7** [maxwroc/battery-state-card#680]
**Describe the bug**
I have a single `entity_id` that will not be excludes.  It works fine for `include`

**How to reproduce**
Add the entity_id (either with wildcard or complete) to exclude list

**Expected behavior**
I expect not to see that entity

**YAML configuration**
```yaml
- type: custom:battery-state-card
  default_state_formatting: false
  title: 'Other'
  sort:
    by: "state"
  collapse:
    - name: 'x{count} at {min}% min'
      min: 90
  colors:
    steps:
      - "#ff0000" # red
      - "#ffff00" # yellow
      - "#00ff00" # green
    gradient: true
  bulk_rename:
    - from: " Battery"
    - from: " Level"
  charging_state:
    state:
      - "Charging"
  filter:
    include:
      - name: entity_id
        value: "sensor.*battery*"
    exclude:
      # motion sensors
      - name: entity_id
        value: "sensor.*_sensor_battery"
      - name: entity_id
        value: "sensor.*_motion_battery"
      # dimmers and switches
      - name: entity_id
        value: "sensor.*smart_button*battery"
      - name: entity_id
        value: "sensor.*dimmer*battery"
      - name: entity_id
        value: "sensor.*bot_*battery" # <- this is the one that still shows
      # contact sensors
        value: "sensor.*_window*battery"
      - name: entity_id
        value: "sensor.*_door*battery*"
      - name: entity_id
        value: "sensor.*_mouse_trap*battery"
      # roller shades
      - name: entity_id
        value: "sensor.*roller_shade*battery"
      # Radiator TRVs
      - name: entity_id
        value: "sensor.*_radiator_battery"
      # counts etc
      - name: entity_id
        value: "*count*"
      - name: entity_id
        value: "*state*"
```

**Dev console errors**
one related to another card

**Screenshots**
"Smartbot Outside Power should not be visible.
![Screenshot 2024-02-11 at 11 52 17](https://github.com/maxwroc/battery-state-card/assets/130979051/856d99ca-1a21-458c-8022-fd9f335f2350)

This is another card with that same entity in `include` filter (working correctly)
![Screenshot 2024-02-11 at 11 53 05](https://github.com/maxwroc/battery-state-card/assets/130979051/3c23c144-08b3-4b52-9a0d-94f3c8adb15d)

**Version**
3.1.6

**Comment by maxwroc** [comment]
What is the actual entity_id which is problematic - on the screenshots I can only see entity name not its ID

**Comment by RedNo7** [comment]
> What is the actual entity_id which is problematic - on the screenshots I can only see entity name not its ID

I highlighted in it the yaml, sorry that wasn't clear.

This the `exclude:`:
```yaml
- name: entity_id
  value: "sensor.*bot_*battery"
```

and this is the full `entity_id`: `sensor.bot_outside_power_battery`

**Comment by sybux** [comment]
I have the same problem since update in january. I have an include and exclude option set as follow :
```
filter:
  include:
    - name: entity_id
      value: '*_battery_plus'
  exclude:
    - name: state
      value: 75
      operator: '>'
```

In my view, the exclude doesn't apply. I have many device with 100% of level
