### ISSUE TITLE
battery icon not showing

### ISSUE THREAD

**Issue by eddysteurs** [maxwroc/battery-state-card#687]
**Describe the bug**
Since a few days the battery icon is not showing, updated to HA2024.2 last week maybe related?
![image](https://github.com/maxwroc/battery-state-card/assets/9960284/f22ed982-919f-4281-867d-02387ed2bb3f)

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config (before backticks below; do not remove them)
type: custom:auto-entities
filter:
  include:
    - attributes:
        device_class: '*battery*'
      state: <101
  exclude:
    - entity_id: '*ramses*'
    - entity_id: '*battery_st*'
    - entity_id: '*binary_se*'
    - entity_id: '*nuc0*'
    - entity_id: '*solis*'
show_empty: true
card:
  type: custom:battery-state-card
sort:
  method: state
  reverse: false
  numeric: true
state_filter:
  - operator: <
    value: 100```

***Entity debug data***
<!-- Add "debug: true" in your card configuration and paste below entity data from the debug output -->

```json

```

**Dev console errors**

**Screenshots**

**Version**
V3.2
