### ISSUE TITLE
Modify tap_action + add hold_action & double_tap_action as per Home Assistant Dashboard Actions for tap actions

### ISSUE THREAD

**Issue by danielbrunt57** [maxwroc/battery-state-card#691]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when... card parameters differ from other mainstream cards.

**Describe the solution you'd like**
Implement the tap_ action configuration variables as per [Home Assistant Actions](https://www.home-assistant.io/dashboards/actions/#tap-action) documentation which the Button, Entities, Glance, Light, Picture, Picture element, Picture entity and Picture glance cards use.

**Additional context**
**_I really want the `confirmation:` option!_**  
And `service_data:` should be just `data:` to match other HA cards.
You could keep `service_data:` functional for backwards compatibility rather than issuing a breaking change.

Ideally, my code would look like...
```
tap_action:
  action: call-service
  confirmation:
    text: Battery replaced?
  service: button.press
  data:
    entity_id: button.bathroom_battery_replaced
```
rather than how I have to do it now...
```
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: button.bathroom_battery_replaced
```
![image](https://github.com/maxwroc/battery-state-card/assets/49846893/24318426-7324-4703-b2f0-1d6228322529)

Oh, and if not too much trouble, could you add `icon_tap_action` like the [tile card](https://www.home-assistant.io/dashboards/tile/) has???

Thanks for listening!

**Comment by danielbrunt57** [comment]
Ideally, I would like to be able to do this with the custom:auto-entities card (and have the confirmation option):
```
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: '{{ this.entity_id|replace("sensor.","button.")|replace("_battery_plus","_battery_replaced") }}'
```
but that is not working.
Full code (thus far)...
```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  title: Low Batteries
  debug: false
  card_mod:
    class: inline-card
filter:
  include:
    - integration: battery_notes
      domain: sensor
      attributes:
        device_class: battery
      state: < 60
      options:
        name: '{attributes.friendly_name} ({attributes.battery_type_and_quantity})'
        secondary_info: 'Last reported: {attributes.battery_last_reported|reltime()}'
        tap_action:
          action: call-service
          service: button.press
          service_data:
            entity_id: '{{ this.entity_id|replace("sensor.","button.")|replace("_battery_plus","_battery_replaced") }}'
    - integration: battery_notes
      domain: binary_sensor
      attributes:
        device_class: battery
      state: 'on'
  exclude:
    - integration: mobile_app
sort:
  method: state
  numeric: true
```
