### ISSUE TITLE
Filter exclude on attribute stopped working in 3.2.0

### ISSUE THREAD

**Issue by andrew-codechimp** [maxwroc/battery-state-card#694]
**Describe the bug**
I have been using the exclude filter on a boolean attribute but with 3.2.0 this has stopped working, ignoring the filter and listing everything.

**How to reproduce**
Add a filter on an attribute, I've flipped it to include or exclude and it doesn't seem to be looking at attributes any more.

**Expected behaviour**
Only show battery_plus entities that have an attribute of battery_low set to false.

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Battery Warnings
round: 0
secondary_info: '{attributes.battery_type_and_quantity}'
filter:
  include:
    - name: entity_id
      value: '*_battery_plus'
  exclude:
    - name: attributes.battery_low
      value: false
bulk_rename:
  - from: Battery+
sort:
  - state
```

***Entity debug data***

```json

```

**Dev console errors**

**Screenshots**

**Version**
3.2.0
