### ISSUE TITLE
Cannot read properties of undefined (reading 'battery_level')

### ISSUE THREAD

**Issue by milandzuris** [maxwroc/battery-state-card#703]
**Describe the bug**
Please check if the problem was reported already
Click [here](https://github.com/maxwroc/battery-state-card/issues?q=is%3Aissue+is%3Aopen+Exception%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27battery_level%27)) to search
If it wasn't please consider creating one
Click [here](https://github.com/maxwroc/battery-state-card/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=Exception%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27battery_level%27)) to create
Please copy-paste the below stack trace.
TypeError: Cannot read properties of undefined (reading 'battery_level')
    at http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:35:10760
    at qt.<anonymous> (http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:35:11567)
    at Generator.next (<anonymous>)
    at http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:1:633
    at new Promise (<anonymous>)
    at e (http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:1:378)
    at qt.internalUpdate (http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:35:9852)
    at qt.<anonymous> (http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:35:2146)
    at Generator.next (<anonymous>)
    at http://dzurishome:8123/hacsfiles/battery-state-card/battery-state-card.js?hacstag=256292682300:1:633

**YAML configuration**
```
type: vertical-stack
cards:
  - type: custom:gap-card
    height: 50
  - type: custom:mushroom-title-card
    title: Batteries
  - type: custom:battery-state-card
    secondary_info: '{attributes.type}'
    entities:
      - entity: sensor.bedroom_motion_battery
        name: Bedroom Motion
      - entity: sensor.bedroom_door_battery
        name: Bedroom Door
      - entity: sensor.bedroom_window_battery
        name: Bedroom Window
      - entity: sensor.bedroom_second_window_battery
        name: Bedroom Second Window
      - entity: sensor.bedroom_thp_battery
        name: Bedroom THP
      - entity: sensor.bedroom_illuminance_battery
        name: Bedroom illuminance
      - entity: sensor.bedroom_button_battery
        name: Bedroom Button
      - entity: sensor.bedroom_window_blinds_battery
        name: Bedroom Window Blinds
      - entity: sensor.living_room_motion_battery
        name: Living Room Motion
      - entity: sensor.living_room_door_battery
        name: Living Room Door
      - entity: sensor.living_room_window_battery
        name: Living Room Window
      - entity: sensor.living_room_second_window_battery
        name: Living Room Second Window
      - entity: sensor.living_room_thp_battery
        name: Living Room THP
      - entity: sensor.living_room_illuminance_battery
        name: Living Room illuminance
      - entity: sensor.living_room_button_battery
        name: Living Room Button
      - entity: sensor.kitchen_motion_battery
        name: Kitchen Motion
      - entity: sensor.kitchen_window_battery
        name: Kitchen Window
      - entity: sensor.kitchen_thp_battery
        name: Kitchen THP
      - entity: sensor.fridge_th_battery
        name: Fridge TH
      - entity: sensor.fridge_door_battery
        name: Fridge Door
      - entity: sensor.kitchen_water_leak_battery
        name: Kitchen Water Leak
      - entity: sensor.kitchen_second_water_leak_battery
        name: Kitchen Second Water Leak
      - entity: sensor.kitchen_button_battery
        name: Kitchen Button
      - entity: sensor.master_bedroom_motion_battery
        name: Master Bedroom Motion
      - entity: sensor.master_bedroom_door_battery
        name: Master Bedroom Door
      - entity: sensor.master_bedroom_window_battery
        name: Master Bedroom Window
      - entity: sensor.master_bedroom_thp_battery
        name: Master Bedroom THP
      - entity: sensor.master_bedroom_button_battery
        name: Master Bedroom Button
      - entity: sensor.guest_room_motion_battery
        name: Guest room Motion
      - entity: sensor.guest_room_door_battery
        name: Guest room Door
      - entity: sensor.guest_room_window_battery
        name: Guest room Window
      - entity: sensor.guest_room_th_battery
        name: Guest room TH
      - entity: sensor.bathroom_motion_battery
        name: Bathroom Motion
      - entity: sensor.bathroom_door_battery
        name: Bathroom Door
      - entity: sensor.bathroom_window_battery
        name: Bathroom Window
      - entity: sensor.bathroom_thp_battery
        name: Bathroom THP
      - entity: sensor.bathroom_water_leak_battery
        name: Bathroom Water Leak
      - entity: sensor.washing_machine_vibration_battery
        name: Washing Machine Vibration
      - entity: sensor.toilet_motion_battery
        name: Toilet Motion
      - entity: sensor.toilet_door_battery
        name: Toilet Door
      - entity: sensor.toilet_window_battery
        name: Toilet Window
      - entity: sensor.toilet_th_battery
        name: Toilet TH
      - entity: sensor.toilet_water_leak_battery
        name: Toilet Water Leak
      - entity: sensor.hallway_motion_battery
        name: Hallway Motion
      - entity: sensor.hallway_door_battery
        name: Hallway Door
      - entity: sensor.hallway_thp_battery
        name: Hallway THP
      - entity: sensor.hallway_button_battery
        name: Hallway Button
      - entity: sensor.technical_room_motion_battery
        name: Technical room Motion
      - entity: sensor.technical_room_door_battery
        name: Technical room Door
      - entity: sensor.technical_room_window_battery
        name: Technical room Window
      - entity: sensor.technical_room_th_battery
        name: Technical room TH
      - entity: sensor.rack_th_battery
        name: Rack TH
      - entity: sensor.technical_room_water_leak_battery
        name: Technical room Water Leak
      - entity: sensor.pantry_motion_battery
        name: Pantry Motion
      - entity: sensor.pantry_door_battery
        name: Pantry Door
      - entity: sensor.pantry_window_battery
        name: Pantry Window
      - entity: sensor.pantry_th_battery
        name: Pantry TH
      - entity: sensor.loft_door_battery
        name: Loft Door
      - entity: sensor.loft_th_battery
        name: Loft TH
      - entity: sensor.patio_motion_battery
        name: Patio Motion
      - entity: sensor.rock_garden_island_smt_battery
        name: Rock Garden Island SMT
      - entity: sensor.shed_th_battery
        name: Shed TH
      - entity: sensor.second_workshop_th_battery
        name: Second Workshop TH
      - entity: sensor.mailbox_battery
        name: Mailbox
      - entity: sensor.mailbox_door_battery
        name: Mailbox Door
      - entity: sensor.dog_button_battery
        name: Dog Button
```

**Screenshots**
![image](https://github.com/maxwroc/battery-state-card/assets/42905545/489d8678-d53b-47d9-baae-ca07d05cb2ff)

**Version**
3.2.1
HA: 2024.2.2
