### ISSUE TITLE
Color not Work

### ISSUE THREAD

**Issue by milandzuris** [maxwroc/battery-state-card#704]
**Describe what is wrong**
Why last Entities don't show Color?

# paste your card configuration here
```
type: custom:battery-state-card
secondary_info: '{last_changed}'
icon: mdi:signal
filter:
  include:
    - name: entity_id
      value: '*linkquality'
  exclude:
    - name: state
      value: '*NaN'
sort:
  by: state
bulk_rename:
  - from: ' linkquality'
    to: ' Linkquality'
value_override: '{state|abs()}'
colors:
  steps:
    - value: 30
      color: '#ff0000'
    - value: 80
      color: '#ffff00'
    - value: 255
      color: '#00ff00'
  gradient: true
```

**Screenshot**
![image](https://github.com/maxwroc/battery-state-card/assets/42905545/afcb9357-71a3-4b50-97b5-b86c0da7ca2c)
