### ISSUE TITLE
Entity already included but nowhere on card even with debug

### ISSUE THREAD

**Issue by heagan01** [maxwroc/battery-state-card#706]
**Describe what is wrong**
So I want to add my laptop's battery percentage (from Hass.Agent) to this card, it has an entity named 

> sensor.desktop_2gbc68r_desktop_2gbc68r_battery_charge_remaining_percentage 

I added it in include with the entity (see YAML configuration below)

**YAML configuration**
```yaml

type: custom:battery-state-card
secondary_info: '{last_changed}'
filter:
  include:
    - name: attributes.device_class
      value: battery
    - name: entity.id
      entity: >-
        sensor.desktop_2gbc68r_desktop_2gbc68r_battery_charge_remaining_percentage
  exclude:
    - name: entity_id
      value: binary_sensor.*
sort:
  by: state
collapse: 8
bulk_rename:
  - from: ' Battery'
  - from: ' level'
colors:
  steps:
    - '#ff0000'
    - '#ffff00'
    - '#00ff00'
  gradient: true
debug: true


```

**Screenshot**

![image](https://github.com/maxwroc/battery-state-card/assets/54394590/4a615512-ca89-4784-b928-339f8c866ebb)
debug only shows these two

**Version**

3.2.1
