### ISSUE TITLE
Wrong display with space separated thousands

### ISSUE THREAD

**Issue by Gonioul** [maxwroc/battery-state-card#709]
**Describe the bug**
Display is wrong with space separated thousands, ex: "1 024 W" is trucated to "1 W"

**YAML configuration**
```yaml
              - type: custom:battery-state-card
                title: Plugs
                unit: W
                icon: mdi:power-plug
                sort:
                  by: state
                  desc: true
                colors:
                  steps:
                    - value: 0
                      color: var(--label-badge-grey)
                    - value: 25
                      color: var(--label-badge-blue)
                    - value: 50
                      color: var(--label-badge-green)
                    - value: 75
                      color: var(--label-badge-yellow)
                    - value: 100
                      color: var(--label-badge-red)
                collapse: 10
                tap_action: more-info
                filter:
                  include:
                    - name: attributes.device_class
                      operator: '='
                      value: power
                  exclude:
                    - name: entity_id
                      operator: matches
                      value: /.*(battery|_electric_w_value).*/
                bulk_rename:
                  - from: / Puissance$/
                  - from: /_power_power$/
```

**Screenshots**
![image](https://github.com/maxwroc/battery-state-card/assets/64291573/72b0af95-ba78-4233-9327-e0b4542b58f2)

**Version**
v3.2.1
