### ISSUE TITLE
Entities listed in card config not displayed; only 15 out of 21 shown

### ISSUE THREAD

**Issue by JoeKae** [maxwroc/battery-state-card#711]
**Describe the bug**

Some of the entities that are listed in the card config are not shown in the card. There are 21 entities added and only 15 are shown. To limit the size of this issue I reduced the config to the 6 missing entities. When I first created the config a few months ago it all worked fine. It must have been broken since an update of the card or of HA but I did not notice it until now.

The entities are also missing if I use the default card config.

Also, there is nothing in the console log.

Maybe it is not important, but the manufacturers of the missing devices are **Motion Blinds** and **Shelly**. There are Shelly devices that show up though.

**How to reproduce**

To enable you to reproduce, I added all the 6 entities below (see "Entity debug data").

**Expected behavior**

The expected behavior is that all of the listed entities in the config are shown in the card. If any error occurs, there should be a console log.

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Battery levels
debug: true
secondary_info: '{last_changed}'
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
sort:
  by: state
collapse:
  - name: 'Thermostate (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    entities:
      - sensor.heizkorper_battery
  - name: 'Rollos (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    entities:
      - sensor.rollerblind_0001_battery
      - sensor.rollerblind_0002_battery
      - sensor.rollerblind_0003_battery
  - name: 'Sensoren (min: {min}%, count: {count})'
    secondary_info: Battery levels {range}%
    entities:
      - sensor.shellydw2_078ccb_battery
      - sensor.fenster_sud_kinderzimmer_battery

entities:
  - entity: sensor.rollerblind_0001_battery
    name: Schlafzimmer Ostfenster
  - entity: sensor.rollerblind_0002_battery
    name: Kinderzimmer Ostfenster
  - entity: sensor.rollerblind_0003_battery
    name: Kinderzimmer Südfenster
  - entity: sensor.heizkorper_battery
    name: Heizkörper Bad
  - entity: sensor.shellydw2_078ccb_battery
    name: Fenstersensor Kinderzimmer Ost
  - entity: sensor.fenster_sud_kinderzimmer_battery
    name: Fenstersensor Kinderzimmer Süd
```

***Entity debug data***

As the entities are not shown at all, there is also no debug output. So I added the info from the HA Dev States.

```yaml
entity_id: sensor.rollerblind_0001_battery
    state: 88.0
    state_class: measurement
    battery_voltage: 12.09
    unit_of_measurement: %
    device_class: battery
    friendly_name: Ostfenster battery

entity_id: sensor.rollerblind_0002_battery
    state: 80.0
    state_class: measurement
    battery_voltage: 11.92
    unit_of_measurement: %
    device_class: battery
    friendly_name: Ostfenster battery

entity_id: sensor.rollerblind_0003_battery
    state: 77.0	state_class: measurement
    battery_voltage: 11.86
    unit_of_measurement: %
    device_class: battery
    friendly_name: Südfenster battery

entity_id: sensor.heizkorper_battery
    state: 99	state_class: measurement
    unit_of_measurement: %
    device_class: battery
    friendly_name: Heizkörper battery

entity_id: sensor.shellydw2_078ccb_battery
    state: 80	state_class: measurement
    unit_of_measurement: %
    device_class: battery
    friendly_name: shellydw2-078CCB battery

entity_id: sensor.fenster_sud_kinderzimmer_battery
    state: 100	state_class: measurement
    unit_of_measurement: %
    device_class: battery
    friendly_name: Fenster Süd Kinderzimmer battery
```

**Dev console errors**

Nothing.

**Screenshots**

Screenshots will be added if the need arises.

**Version**
```yaml
battery_state_card: 3.2.1
home_assistant:
    - core: 2024.3.0
    - supervisor: 2024.02.1
    - operating_system: 12.0
    - frontend: 20240306.0
```
