### ISSUE TITLE
Add support for name_template

### ISSUE THREAD

**Issue by Superkikim** [maxwroc/battery-state-card#728]
**Is your feature request related to a problem? Please describe.**
I use autoentity to get the state of all batteries in my home assistant. I'd like to extract the device name, rather than have the entity name showed by the battery-state-card. Unfortunately, it seems name_template is not supported by battery-state-card.

In the example below, name_template is ignored:

```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  name_template: '{{ device_attr(config.entity, "name_by_user") or device_attr(config.entity, "name") or state_attr(config.entity, "friendly_name") }}'
filter:
  include:
    - entity_id: '*battery*'
      options:
        tap_action:
          action: more-info
  exclude:
    - entity_id: '*state'
    - entity_id: '*health'
    - entity_id: '*power'
    - entity_id: '*temperature'
    - entity_id: '*range'
    - domain: binary_sensor
sort:
  method: state
  reverse: false
  numeric: true
  ```

**Describe the solution you'd like**
Add the support for name_template to battery-state-card so we can automate and customize entity naming

**Additional context**
Well, I believe the above description says it all ;-)

**Comment by maxwroc** [comment]
Cards cannot evaluate the Ninja templates I think. From what I know Ninja is evaluated on the server/python side. 

If you know any card which supports dynamic ninja templates evaluation please let me know.

I'm closing this item as it is pretty old and I'm trying to clean up the issues list. But feel free to create a new one and reference this if you want to discuss this idea further

**Comment by Superkikim** [comment]
I forgot about this issue. Sorry. I ended up with this which seems to work fine :

```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  name_template: "{{ device_attr(config.entity, \"name\") }}"
filter:
  include:
    - entity_id: "*battery*"
      attributes:
        unit_of_measurement: "%"
      options:
        tap_action:
          action: more-info
  exclude:
    - entity_id: "*state"
    - entity_id: "*health"
    - entity_id: "*power"
    - entity_id: "*temp*"
    - entity_id: "*range"
    - state: un*
    - domain: binary_sensor
sort:
  method: state
  reverse: false
  numeric: true

```
