### ISSUE TITLE
Bulk rename not being applied

### ISSUE THREAD

**Issue by parautenbach** [maxwroc/battery-state-card#729]
**Describe the bug**
`bulk_rename` isn't being applied.

**How to reproduce**
Use the problematic YAML below.

**Expected behavior**

Here, the "Battery" text is removed:

<img width="502" alt="Screenshot 2024-07-05 at 16 08 45" src="https://github.com/maxwroc/battery-state-card/assets/743320/2a2d4ffd-d637-49a3-8864-76cf38fd83ca">

```
        - type: custom:battery-state-card
          title: Battery Charge Levels
          filter:
            include:
              - name: "attributes.monitor"
                value: True
          bulk_rename:
            rules:
              - from: "Battery"
          sort:
            - "name"
```

**YAML configuration**

This doesn't work:

<img width="501" alt="Screenshot 2024-07-05 at 16 08 54" src="https://github.com/maxwroc/battery-state-card/assets/743320/a3213a46-b333-4d4d-a3ed-4dddfd56bbdc">

```yaml
        - type: custom:auto-entities
          debug: true
          card:
            type: entities
            title: Battery Maintenance
          filter:
            include:
              - entity_id: "button.*_battery_replaced"
          bulk_rename:
            rules:
              - from: "Battery"
          sort:
            - "name"
```

***Entity debug data***

There's no debug output (see the debug setting being set in the YAML above):

<img width="525" alt="Screenshot 2024-07-05 at 16 08 36" src="https://github.com/maxwroc/battery-state-card/assets/743320/2dbeb350-d371-4586-9039-40e721725e4c">

```json

```

**Dev console errors**
None.

**Screenshots**
See above.

**Version**
1.13.0
