### ISSUE TITLE
Custom icon colors outside 0-100 range not working

### ISSUE THREAD

**Issue by GeoffWy** [maxwroc/battery-state-card#735]
... we can take the value range which user provided in steps and treat them as the maximum supported range, this way any incoming value can be converted to 0-100 based on such supported range e.g.
```yaml
color:
  steps:
    - value: -3
      color: #ff0000
    - value: 0
      color: #ffff00
    - value: 7
      color: #00ff00
  gradient: true
```

  * -3 will be treated as 0
  * 0 as 30
  * 7 as 100

And this is what will be passed to the `getGradientColors `, so the gradient can be calculated properly

_Originally posted by @maxwroc in https://github.com/maxwroc/battery-state-card/issues/599#issuecomment-1873011076_

**Comment by wilrino** [comment]
I also try to use thresholds function, like this example "{state|thresholds(22,89,200,450)}" but I don't able to use. I don't find any example over the web.

**Comment by wilrino** [comment]
For now I use this solution with template-entity-row and card_mod

I haven't found a solution to avoid repeating all the code that manages the icon color for each entity

`type: entities
entities:
  - type: custom:template-entity-row
    entity: sensor.shellyem_generale_channel_1_power
    name: Generale
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.shellyem_generale_channel_1_power') | float > 1000 %} red;
          {% elif states('sensor.shellyem_generale_channel_1_power') | float > 200 %} orange;
          {% elif states('sensor.shellyem_generale_channel_1_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
  - type: custom:template-entity-row
    entity: sensor.shellyem_generale_channel_2_power
    name: Cucina
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.shellyem_generale_channel_2_power') | float > 1000 %} red;
          {% elif states('sensor.shellyem_generale_channel_2_power') | float > 200 %} orange;
          {% elif states('sensor.shellyem_generale_channel_2_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
      
  - type: custom:template-entity-row
    entity: sensor.smart_plug_bimby_power
    name: Bimby
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.smart_plug_bimby_power') | float > 1000 %} red;
          {% elif states('sensor.smart_plug_bimby_power') | float > 200 %} orange;
          {% elif states('sensor.smart_plug_bimby_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
   
  - type: custom:template-entity-row
    entity: sensor.presa_tuya_zigbee_power
    name: Lavatrice
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.presa_tuya_zigbee_power') | float > 1000 %} red;
          {% elif states('sensor.presa_tuya_zigbee_power') | float > 200 %} orange;
          {% elif states('sensor.presa_tuya_zigbee_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
   
  - type: custom:template-entity-row
    entity: sensor.presa_frigo_nuovo_power
    name: Frigorifero
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.presa_frigo_nuovo_power') | float > 1000 %} red;
          {% elif states('sensor.presa_frigo_nuovo_power') | float > 200 %} orange;
          {% elif states('sensor.presa_frigo_nuovo_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
  - type: custom:template-entity-row
    entity: sensor.shelly_pm_caldaia_power
    name: Caldaia
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.shelly_pm_caldaia_power') | float > 1000 %} red;
          {% elif states('sensor.shelly_pm_caldaia_power') | float > 200 %} orange;
          {% elif states('sensor.shelly_pm_caldaia_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
  - type: custom:template-entity-row
    entity: sensor.clima_potenza_ist
    name: Climatizzatore
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.clima_potenza_ist') | float > 1000 %} red;
          {% elif states('sensor.clima_potenza_ist') | float > 200 %} orange;
          {% elif states('sensor.clima_potenza_ist') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
  - type: custom:template-entity-row
    entity: sensor.smartplug_luci_power
    name: Luci trave
    card_mod:
      style: |
        :host {
          --card-mod-icon-color: 
          {% if states('sensor.smartplug_luci_power') | float > 1000 %} red;
          {% elif states('sensor.smartplug_luci_power') | float > 200 %} orange;
          {% elif states('sensor.smartplug_luci_power') | float > 5 %} green;
          {% else %} gray;
          {% endif %};
        }
           
      `

<img width="296" alt="Screenshot 2024-11-16 alle 10 45 59" src="https://github.com/user-attachments/assets/883f80a0-9d1e-4918-8d49-7fb8fea325eb">

**Comment by ppastur** [comment]
I am also experiencing the same issue.  I believe this is a duplicate [#753 ](https://github.com/maxwroc/battery-state-card/issues/753) .

**Comment by GeoffWy** [comment]
This is my solution using custom:auto-entities and custom:button-card:
```type: custom:auto-entities
card:
  type: entities
  state_color: false
sort:
  method: state
  numeric: true
filter:
  include:
    - entity_id: "*temperature"
      options:
        type: custom:button-card
        show_state: true
        size: 60%
        styles:
          card:
            - height: 40px
            - line-height: null
            - font-size: 14px
            - border: 0px
          name:
            - justify-self: left
          grid:
            - height: 40px
            - grid-template-areas: "\"i n s\""
            - grid-template-columns: .4fr 2fr 1fr
          icon:
            - position: absolute
            - left: 20%
            - color: |-
                [[[
                  var min = 0; var max = 25; var base = max - min;
                  var perc = 100*(entity.state - min)/base;
                  var r = 0; var g = 0; var b = 0;
                  if (perc <0 ) perc=0;
                  if (perc >100) perc=100;
                  if (perc < 25 ) {
                    var b = 255;
                    var g = parseInt(10.2 * perc);
                  } else if (perc < 50 ) {
                    perc = perc - 25;
                    var g = 255;
                    var b = parseInt(255 - 10.2 * perc);
                  } else if (perc < 75 ) {
                    perc = perc - 50
                    var g = 255;
                    var r = parseInt(10.2 * perc);
                  } else {
                    perc = perc - 75;
                    var r = 255;
                    var g = parseInt(255 - 10.2 * perc);
                  }
                  var h = r * 0x10000 + g * 0x100 + b * 0x1;
                  return '#' + ('000000' + h.toString(16)).slice(-6);
                ]]]
  exclude: []
show_empty: true
```
<img src="https://github.com/user-attachments/assets/08161ad5-eea7-4c2f-8eb6-c55e6d22cd0e" width="300" >

**Comment by RobertoCravallo** [comment]
Such a great card, but unfortunately the colors setting only works from 0-100, no matter what is set under "colors:". This needs to be "fixed" and would make the card near perfect!!!

**Comment by maxwroc** [comment]
Setting the colors for other ranges is possible now in v3.3 hence closing

**Comment by wilrino** [comment]
Thank you maxwroc for the notification!

But I tried the code and it doesn't work. (In example "generale" are > 100 and it is white) 
What am I doing wrong in the syntax?

<img width="980" height="617" alt="Image" src="https://github.com/user-attachments/assets/f03a3422-e6a5-4a49-b92e-a823ab9d51e7" />

I also tried reversing the order of color and value after steps: as I found in an example but the result is the same.

```
type: custom:battery-state-card
icon: mdi:flash
colors:
  steps:
    - value: 10
      color: "#00ff00"
    - value: 100
      color: "#ffff00"
    - value: 10000
      color: "#ff0000"
entities:
  - entity: sensor.shellyem_generale_channel_1_power
    name: generale
  - entity: sensor.shellyem_generale_channel_2_power
    name: Cucina
  - entity: sensor.smartplug_luci_power
    name: Luci trave
  - entity: sensor.clima_potenza_ist
    name: Climatizzatore
  - entity: sensor.presa_zigbee_6_power
    name: Bimby
  - entity: sensor.presa_tuya_zigbee_power
    name: Lavatrice
  - entity: sensor.presa_frigo_nuovo_power
    name: Frigo
  - entity: sensor.shelly_pm_caldaia_power
    name: Caldaia
charging_state: false
units: W
```

**Comment by maxwroc** [comment]
@wilrino I think that you are not on v3.3

I cannot repro:

```yaml
type: custom:battery-state-card
icon: mdi:flash
colors:
  steps:
    - value: 10
      color: "#00ff00"
    - value: 100
      color: "#ffff00"
    - value: 10000
      color: "#ff0000"
filter:
  include:
    - name: entity_id
      value: "*_power"
charging_state: false
units: W
sort:
  by: state
  desc: true
```

<img width="986" height="588" alt="Image" src="https://github.com/user-attachments/assets/8176ea3a-1f41-47c6-83c2-0c08d5112675" />
