### ISSUE TITLE
Filter entities seen recently

### ISSUE THREAD

**Issue by doppynl** [maxwroc/battery-state-card#736]
Can I exclude entities that have been seen recently?

Why? This way I can list entities that haven't been seen for 24 hours or more, even though their battery might be set as high enough, the battery might have died.

**YAML configuration**
Something like:
```yaml

  exclude:
    - name: "{last_updated}"
      value: '{{ now() - timedelta( hours = 24 ) }}'
      operator: ">"

```
**Version**
most recent.
