### ISSUE TITLE
Card name not showing

### ISSUE THREAD

**Issue by Generalnoob** [maxwroc/battery-state-card#737]
Hi I'm trying to set up the card, everything works perfectly but the card name doesn't show up, any help would be greatly appreciated :)

**YAML configuration**
```yaml

type: custom:battery-state-card
name: Kids Phones
secondary_info: '{last_updated}'
entities:
  - entity: sensor.kidname1_mobile_battery_level
    name: kidname1's Mobile
    secondary_info: '{charging}'
    charging_state:
      attribute:
        name: is_charging
        value: true
  - entity: sensor.kidname2_mobile_battery_level
    name: kidname2's Mobile
    secondary_info: '{charging}'
    charging_state:
      attribute:
        name: is_charging
        value: true

```

**Screenshot**
![image](https://github.com/user-attachments/assets/bd0c75aa-36a8-417e-9315-9907b81eef87)

**Version**
v3.2.1
