### ISSUE TITLE
reltime() seems broken, just adds literal "<rt>" tag

### ISSUE THREAD

**Issue by magicus** [maxwroc/battery-state-card#738]
**Describe the bug**

I tried to copy the example in the docs, and added:
```
value_override: '"Changed: {last_changed|reltime()}"'
```
to my card. However, this does not result in relative times, but instead an output like:
```
"Changed: <rt>2024-08-26T21:53:45.731Z</rt>
```

**How to reproduce**
Add the `reltime()` function in a template.

**Expected behavior**
I expected a relative time, like `5 minutes ago`.

**YAML configuration**
```yaml
type: custom:battery-state-card
title: Battery levels
value_override: '"Changed: {last_changed|reltime()}"'
non_battery_entity: true
default_state_formatting: false
filter:
  include:
    - name: entity_id
      value: '*_last_seen'
unit: null
sort:
  - state
```

***Entity debug data***

```json

```

**Dev console errors**

**Screenshots**

**Version**
