### ISSUE TITLE
Can't implicitly include

### ISSUE THREAD

**Issue by craigmcfly** [maxwroc/battery-state-card#741]
```
type: custom:battery-state-card
filter:
  include:
      - name: "attributes.device_class"
        value: "battery"
  exclude:
      - name: "entity_id"
        value: "*blah*"
```

will work

but

```
type: custom:battery-state-card
filter:
  exclude:
      - name: "entity_id"
        value: "*blah*"
```

will not. Not sure if this is a bug or just something that needs to be explicitly made clear in the documentation.
