### ISSUE TITLE
name and battery percentage status unde icon

### ISSUE THREAD

**Issue by Hadatko** [maxwroc/battery-state-card#745]
**Is your feature request related to a problem? Please describe.**
Hi i am using grid panel. In that i want 4 columns. Each column will contains several battery states. I would like to have any text information bellow icon.

**Describe the solution you'd like** 
I would like to have any text information bellow icon.
I would also like to hide value, as icon is good enough representative.

**Additional context**
Currently it looks terrible and i don't see name as there no space left on a side:
![image](https://github.com/user-attachments/assets/c35aff9b-2584-49c9-b01b-5af0b0d5b957)

**Comment by Hadatko** [comment]
This is what i know how to do. As you can see this is one panel contains 4xbatery status cards. If i could hide value and move name under icon it would be top ;)

![image](https://github.com/user-attachments/assets/9bf03467-af81-434b-931a-f3fadf641a63)

**Comment by hilburn** [comment]
You can *kind of* hide the percentage but it's hideous

```
state_map:
  - from: "100"
    to: "100"
    display: " "
  - from: "97"
    to: "97"
    display: " "
   ...
```
obviously this gets very silly very quickly

**Comment by Hadatko** [comment]
Hopefully some simpler and nicer solution will show up. But thank you for your idea.

**Comment by hilburn** [comment]
You can get them to display vertically rather than horizontally with card-mod:

```yaml
card_mod:
  style: |
    battery-state-entity {
      flex-direction: column;
    }
```
![image](https://github.com/user-attachments/assets/a221ce5a-ede4-422a-8c2f-83222918ec80)


I'm not good enough with card-mod to work out how to hide the state using that - iirc it should be something like `battery-state-entity$:.state {display: none;}` but I wasn't able to make it work
