### ISSUE TITLE
Filter for integration?

### ISSUE THREAD

**Issue by Stephan-4711** [maxwroc/battery-state-card#746]
How can I achive, to add the card for just one integration?

For example Homematic only delivers a state batterie low no/yes.

I want one card just for the Homematic integration, 

To get a more clear view.

**Comment by maxwroc** [comment]
It is not possible now unfortunately but I have this in mind... maybe around Christmas time I'll find a bit more time to develop the card

**Comment by GottZ** [comment]
> It is not possible now unfortunately but I have this in mind... maybe around Christmas time I'll find a bit more time to develop the card

that's nice! looking forward to it, as I'm currently just doing it like this right now:

```yaml
filter:
  include:
    - name: entity_id
      value: sensor.*.battery_plus
    - name: entity_id
      value: sensor.jan_battery_level
    - name: entity_id
      value: sensor.sm_s921b_battery_level
```
