### ISSUE TITLE
Please fix compatibility with HA-Battery-Notes action buttons

### ISSUE THREAD

**Issue by cniry** [maxwroc/battery-state-card#751]
Your battery state card is awesome, but in one use-case I need to use it with [HA-Battery-Notes](https://github.com/andrew-codechimp/HA-Battery-Notes) entities.

HA-Battery-Notes creates entities with manual buttons "Battery replaced".

In classic entity card, this renders an action buttons correctly: 
![image](https://github.com/user-attachments/assets/4dd18fc9-2c0e-43fa-ba49-7b715b12d6fd)

In battery-state-card, it renders only static values instead of buttons: 
![image](https://github.com/user-attachments/assets/243b1b28-aab6-4380-83b4-373740e6b939)

Is possible to render these action buttons?

**Comment by maxwroc** [comment]
Thanks for the suggestion. I'm planning to integrate battery notes features into the card and this one is on my list

**Comment by Morphy99** [comment]
I've managed to do this with the [Auto entities custom card:](https://github.com/thomasloven/lovelace-auto-entities)

```
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - options:
        secondary_info: state
      integration: INTEGRATION ID FOR BATTERY NOTES
      entity_id: button.*
      sort:
        method: friendly_name
  exclude: []

```
