### ISSUE TITLE
Feature Request: LQI (Link Quality Indicator) State Card

### ISSUE THREAD

**Issue by MarvinMynx** [maxwroc/battery-state-card#752]
For Zigbee2MQTT devices, you can enable the LQI statistics which can then be displayed in dashboards or custom cards. I'm wondering if you would be able to add a whole new custom dashboard card called "lqi-state-card" or something similar, which would display the LQI entities similar to the battery states, with gradient coloring depending on the LQI, sorting from bad to good signal, and an expandable menu just like in the battery-state-card.

**Comment by MarvinMynx** [comment]
I was able to get close using the existing card and some examples, but I'm a little stuck.
This is what I have right now:

```yaml
type: custom:battery-state-card
secondary_info: "{last_changed}"
icon: "mdi:signal-cellular-{state|
    abs()|
    lessthan(64,outline)|
    lessthan(128,1)|
    lessthan(192,2)|
    greaterthan(192,3)
}"
colors:
  steps:
    - value: 64 # bad signal
      color: "#FF0000"
    - value: 128 # poor signal
      color: "#FFA500"
    - value: 192 # moderate signal
      color: "#FFFF00"
    - value: 255 # excellent signal
      color: "#00FF00"
  gradient: true
filter:
  include:
    - name: entity_id
      value: sensor.*_linkquality
  exclude:
    - name: entity_id
      value: binary_sensor.*
    - name: entity_id
      value: sensor.2312dra50g*
sort:
  - by: state
    desc: true
collapse: 8
bulk_rename:
  - from: " Linkquality"
```
In Zigbee2MQTT entities, the LQI goes from 255 (good) to 0 (bad).
The only problem I have is that I can't figure out how to provide the dynamic icons correctly. Right now, a device with an LQI of 120 will get displayed at 2 bars for some reason.
And the coloring doesn't work at all. Basically, I want to replicate the same coloring and icon behavior as the default values of this card for the battery status, just for the linkquality sensor instead of the battery one.
Can you help me with these two issues? (This would make an additional great example on the README.md of this project, adding to the RSSI section)

**Comment by MarvinMynx** [comment]
I fixed the Icon Problem with the use of between in addition to lessthan and greaterthan, but still no Luck on Colors at All ^^"
```yaml
type: custom:battery-state-card
secondary_info: "{last_changed}"
icon: >-
  mdi:signal-cellular-{state| abs()| lessthan(64,outline)| between(64,128,1)|
  between(128,192,2)| greaterthan(191,3) }
value_override: "{state|abs()}"
unit: LQI
round: 0
colors:
  steps:
    - color: red
      value: 64
    - color: yellow
      value: 192
    - color: green
      value: 255
  gradient: true
filter:
  include:
    - name: entity_id
      value: sensor.*_linkquality
  exclude:
    - name: entity_id
      value: binary_sensor.*
    - name: entity_id
      value: sensor.2312dra50g*
sort:
  - by: state
    desc: false
collapse: 8
bulk_rename:
  - from: " Linkquality"
  - from: " Signal"
  - from: " strength"
  - from: " Rssi"
  - from: " numeric"
```
