### ISSUE TITLE
Battery State is not displaying when device is charging

### ISSUE THREAD

**Issue by ID-Ant** [maxwroc/battery-state-card#754]
**Describe what is wrong**
When the device is Charging, the icon and secondary_info_text is not changing

**YAML configuration**
```yaml

type: custom:battery-state-card
secondary_info: "{last_updated}"
sort:
  by: state
entities:
  - entity: sensor.id_hotspot_battery_level
    name: Ant iPhone
    secondary_info: null
  - entity: sensor.id_ipad_battery_state
  - entity: sensor.id_ipad_battery_level
    name: iPad Kiosk
    secondary_info: "{charging}" # only appears when charging is detected
    charging_state:
      attribute:
      - name: "Battery State"
        value: "Charging"
      secondary_info_text: "Charging in progress" # override for "Charging" text
      color: yellow
      icon: mdi:battery-charging


```

**Screenshot**
<img width="1001" alt="Screenshot 2024-12-16 at 10 32 11" src="https://github.com/user-attachments/assets/0cb20cdf-c7a3-4461-8389-2be12ed38ef0" />

**Version**
release: v3.2.1

**Comment by dfhsingh** [comment]
For my Android (Pixel 7a) the charging icon is correctly displayed, but not for my iOS devices (iPhone and iPad).
I found that the battery_state for Android is 'charging' (lower case) but for iOS devices its 'Charging' (sentence case)

**Comment by maxwroc** [comment]
If you were planning to get the state from the other entity then it should be done in a different way - you need to provide the entity_id and the value is taken from the state not attribute. Sth like:
```yaml
charging_state:
  entity_id: sensor.id_ipad_battery_state
  state:
    - charging
    - Charging
```
