### ISSUE TITLE
Show negative numbers?

### ISSUE THREAD

**Issue by petterca** [maxwroc/battery-state-card#755]
**I'm currently using a battery-state-card to visualize a range of temperatures in my Home Assistant setup. While I'm quite satisfied with the card overall, I've encountered an issue where it seems unable to display negative temperature values. Could you please advise on how I can configure the card to correctly show negative temperatures?**

**YAML configuration**
```yaml

# type: custom:battery-state-card
title: Temperaturer
icon: mdi:thermometer
colors:
  steps:
    - value: -1
      color: blue
    - value: 15
      color: green
    - value: 20
      color: yellow
    - value: 25
      color: orange
    - value: 30
      color: red
tap_action:
  action: more-info
collapse: 3
sort: state
reverse: true
unit: °C
value: |
  {{ states('sensor.temperature_sensor') | float }}
entities:
  - entity: sensor.inne_matsal_temperature
    name: matsal
  - entity: sensor.vrum_multisensor1_temperatur
    name: Vardagsrum
  - entity: sensor.hall_rorelsesensor_uppe_temperatur
    name: Hall uppe
  - entity: sensor.hall_rorelsesensor_nere_temperatur
    name: Hall nere
  - entity: sensor.kok_multisensor2_temperature
    name: Multisensor i lilla kösfönstret
  - entity: sensor.kok_fuktsensor_temperatur
    name: Under kylen
  - entity: sensor.tvattkallaren_rorelsesensor_temperature
    name: Tvättkällaren
  - entity: sensor.ute_temperatur_temperature
    name: Utetemperatur
  - entity: sensor.hall_rokvarnare_temperature
    name: Rökvarnare
  - entity: sensor.vrum_termometer_a_temperature

```

**Screenshot**

**Version**

v3.2.1

**Comment by maxwroc** [comment]
Maybe something like the following?

```yaml
type: custom:battery-state-card
filter:
  include:
    - name: attributes.device_class
      value: temperature
  exclude:
    - name: state
      value: Unavailable
icon: "mdi:thermometer"
sort: state
bulk_rename:
  - from: temperature
  - from: Temperature
  - from: Current
  - from: Device
colors:
  steps:
    - color: "#0000ff"
      value: 5
    - color: "#ff0000"
      value: 40
  gradient: true
  non_percent_values: true
```

<img width="985" height="502" alt="Image" src="https://github.com/user-attachments/assets/86514e28-d128-40a1-90f4-be20b65f1583" />

Make sure you are on v3.3 +
