### ISSUE TITLE
Compatibility with card-mod

### ISSUE THREAD

**Issue by mistic100** [maxwroc/battery-state-card#757]
**Describe the bug**

I seems this card is not compatible with [card-mod](https://github.com/thomasloven/lovelace-card-mod). Or I am doing it wrong ?

**How to reproduce**

This is my configuration, I try to reduce the spacing between each item.

```yml
type: custom:battery-state-card
filter:
  include:
    - name: attributes.device_class
      value: battery
card_mod:
  style: |
    .entity-spacing {
      margin: 0;
    }
```

The style is not applied. When I inspect the DOM, I don't see any `card-mod` component near `ha-card`.

![Capture d’écran du 2025-01-10 16-56-07](https://github.com/user-attachments/assets/9d2dd8f0-f403-4dda-88a0-9a03b335ee0b)

----

For comparison I also use mini-graph-card and here the card-mod is injected.

```yml
type: custom:mini-graph-card
entities:
  - entity: sensor.thermometre_sejour_humidity
  - entity: sensor.thermometre_chambre_humidity
card_mod:
  style: |
    .states > .state {
      display: none;
    }
    .state--small {
      font-size: 1em;
    }
```

![Capture d’écran du 2025-01-10 16-55-34](https://github.com/user-attachments/assets/0f5debf6-4eb8-4002-a693-d1a4f01d91a9)

**Dev console errors**

No errors

**Screenshots**

**Version**
MULTIPLE-ENTITY-ROW  4.5.1 
BATTERY-STATE-CARD  3.2.1
CARD-MOD 3.5.0 
MINI-GRAPH-CARD  0.12.1 
XIAOMI-VACUUM-MAP-CARD   v2.2.4           
CLOCK-WEATHER-CARD   2.8.7
SCHEDULER-CARD   v3.2.13
🍄 Mushroom 🍄 - 4.2.1
APEXCHARTS-CARD  v2.1.2
