### ISSUE TITLE
Automatic grouping by device

### ISSUE THREAD

**Issue by sikraemer** [maxwroc/battery-state-card#758]
**Is your feature request related to a problem? Please describe.**
Hey,

I have some devices that provide both a percentage value as well as a battery low state.
(e.g. using the [Battery Notes](https://github.com/andrew-codechimp/HA-Battery-Notes) integration).
For other devices I only have the battery low state.

In cases where both values are available the current solution does not allow to exclude one of them, which makes the same device appear twice.

**Describe the solution you'd like**
It would be nice to automatically group entities by the device they are part of.

**Additional context**
![image](https://github.com/user-attachments/assets/d63e1935-1797-4b65-b816-500e51233dc2)
![image](https://github.com/user-attachments/assets/4bc22d18-632c-41a1-b9bf-5daae3f43bce)

```yaml
type: custom:battery-state-card
title: Battery States
secondary_info: "{attributes.battery_type_and_quantity}"
round: 0
filter:
  include:
    - name: entity_id
      value: "*_battery_plus"
    - name: entity_id
      value: "*_battery_plus_low"
bulk_rename:
  - from: Battery+
  - from: Battery low
state_map:
  - from: "off"
    to: 100%
  - from: "on"
    to: 10%
collapse: 5
sort:
  - state
  - name
```

![image](https://github.com/user-attachments/assets/357d5919-7976-4d88-b69b-38923a8a9f69):
![image](https://github.com/user-attachments/assets/97ad0d1c-de49-4e47-9a62-40b6cd4ebc75)
