### ISSUE TITLE
Exclude entities from a entities specification

### ISSUE THREAD

**Issue by bcutter** [maxwroc/battery-state-card#759]
**Describe what is wrong**

I specify a group of entities. I want to hide entities of that group which are of state unknown, unavailable etc. I think the filter / exclude does not work here, does it?

**YAML configuration**
```
type: custom:battery-state-card
entities:
  - entity: group.batterystate_devices
title: 📱 Geräte
secondary_info: '{last_updated}'
tap_action: more-info
sort:
  by: state
  desc: false
collapse: 12
filter:
  exclude:
    - name: state
      value: unknown
round: 0
unit: '%'
colors: null
default_state_formatting: false
bulk_rename:
  - from: ' Battery Level'
    to: ''
  - from: ' Battery level'
    to: ''
  - from: ' Akkufüllstand'
    to: ''
  - from: ' Batterieladung'
    to: ''
  - from: ' Batteriestand'
    to: ''
```

**Screenshot**
![image](https://github.com/user-attachments/assets/cbb405a7-3e61-4eb8-9173-4f9a04218f72)<!— Add a screenshot if applicable —>

**Version**
V3.2.1
