### ISSUE TITLE
Help with either grouping or value override

### ISSUE THREAD

**Issue by ppastur** [maxwroc/battery-state-card#760]
**Describe what is wrong**
Value override OR Grouping doesn't seem to work as expected (or rather more likely, I have misconfigured something).

I have set up the card to display Zigbee sensor LQI % strength.  I am trying to collapse them into groups. As you will see from the screenshot, some sensors don't seem to want to collapse into their group.  

I would really appreciate some help to figure this out.

BTW - I love this card - thank you

**YAML configuration**
```yaml

type: custom:battery-state-card
title: Zigbee sensor LQI
secondary_info: "{last_updated}"
icon: >-
  mdi:signal-cellular-{state| abs()| lessthan(64,outline)| between(64,128,1)|
  between(128,192,2)| greaterthan(191,3) }
unit: LQI
colors:
  steps:
    - "#ff2d55"
    - "#f4bc00"
    - "#00ff00"
  gradient: true
filter:
  include:
    - name: attributes.unit_of_measurement
      value: lqi
    - name: entity_id
      value: "*_Linkquality"
sort:
  by: state
collapse:
  - name: LQI  0-39%
    secondary_info: "{count} sensors"
    min: 0
    max: 39
  - name: LQI  40-90%
    secondary_info: "{count} sensors"
    min: 40
    max: 90
  - name: LQI  91-100%
    secondary_info: "{count} sensors"
    min: 91
bulk_rename:
  - from: " Linkquality"
value_override: >-
  {state|between(0,14,5)|between(15,26,10)|between(27,39,15)|between(40,52,20)|between(53,65,25)|between(66,77,30)|between(78,90,35)|between(91,103,40)|between(104,117,45)|between(117,128,50)|between(129,141,55)|between(142,154,60)|between(155,167,65)|between(168,179,70)|between(180,193,75)|between(193,205,80)|between(206,218,85)|between(219,230,90)|between(231,243,95)|between(244,256,100)}


```

**Screenshot**

![Image](https://github.com/user-attachments/assets/d0478232-66ba-4954-a593-05ed3e6c2f61)

![Image](https://github.com/user-attachments/assets/0fcceeac-970c-43d1-a150-846a8180ad58)

**Version**

v3.2.1
