### ISSUE TITLE
Adding filter changes colors and order

### ISSUE THREAD

**Issue by waclaw66** [maxwroc/battery-state-card#761]
**Describe the bug**
I would like to include multiple `binary_sensor` entities that states empty battery on value "On". 

Originally it looks like this...

```yaml
type: custom:battery-state-card
```
![Image](https://github.com/user-attachments/assets/e7ee7dde-d703-4c1d-88b3-31001045eb30)|

When I add filter with state mapping it's showed like this...

```yaml
type: custom:battery-state-card
filter:
  include:
    - name: "attributes.device_class"
      value: "battery"
  exclude:
    - name: state
      value: Off
state_map:
  - from: 'on'
    to: 0
    display: empty
```

![Image](https://github.com/user-attachments/assets/d6603013-ead6-4dbe-a729-2421cc853891)

The `filter` causes that colors are degraded and order is wrong.

**How to reproduce**

**Expected behavior**

**YAML configuration**
```yaml

# please paste here your card config (before backticks below; do not remove them)

```

***Entity debug data***

```json

```

**Dev console errors**

**Screenshots**
above

**Version**
v3.2.1
