### ISSUE TITLE
Sorting issue with having a thousands separators

### ISSUE THREAD

**Issue by kotnik** [maxwroc/battery-state-card#769]
**Describe the bug**

Sorting with `default_state_formatting` is wrong. Please take a look at the screenshot which best describes this issue:

![](https://bin.kotur.org/25tzxGtOH8Ppjv.png)

Of course, sorting is correct when `default_state_formatting: false` is set.

**YAML configuration**
```yaml

type: custom:battery-state-card
icon: mdi:power-plug
filter:
  include:
    - name: attributes.device_class
      value: power
  exclude:
    - name: attributes.friendly_name
      value: Power plugs
    - name: attributes.friendly_name
      value: Renault Twingo III Admissible charging power
sort:
  by: state
  desc: true
colors:
  steps:
    - value: 50
      color: green
    - value: 100
      color: blue
    - value: 200
      color: yellow
    - value: 500
      color: red
bulk_rename:
  - from: " ENERGY Power"
  - from: "Plug "
  - from: Power socket
  - from: "Socket "
  - from: " Power"

```

**Version**

v.3.2.1
