### ISSUE TITLE
Battery Groups Not Expanding On Mobile Browsers

### ISSUE THREAD

**Issue by townsmcp** [maxwroc/battery-state-card#84]
**Describe the bug**
I have installed the card and added battery groups to a custom card.
On Safari and Chrome, the group works (expand and collapsing) however on Mobile Safari (ipad and iphone) and Mobile Chrome, the expand button doesnt drop down the list.
Also tried expanding from in the HA mobile app but this didnt work either.

**How to reproduce**
Configure with group option

**Expected behavior**
Click the drop down on mobile devices and the list expands to show defined entities

**YAML configuration**

# please paste here your card config

```
type: 'custom:battery-state-card'
title: Battery State Card
sort_by_level: asc
collapse:
  - name: 'Door Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:door'
    entities:
      - sensor.front_door_door_sensor_battery
      - sensor.back_door_sensor_battery
      - sensor.under_stairs_sensor_battery
  - name: 'Wardrobe Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:wardrobe-outline'
    entities:
      - sensor.master_bedroom_wardrobe_left_sensor_battery
      - sensor.master_bedroom_wardrobe_right_sensor_battery
  - name: 'Downstairs Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:home-floor-g'
    entities:
      - sensor.downstairs_hall_sensor_battery
      - sensor.front_door_sensor_battery
      - sensor.dining_room_sensor_battery
      - sensor.kitchen_sensor_battery
      - sensor.lounge_tv_sensor_battery
      - sensor.lounge_sofa_sensor_battery
      - sensor.garden_sensor_battery
  - name: 'Upstairs Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:home-floor-1'
    entities:
      - sensor.bottom_of_stairs_sensor_battery
      - sensor.car_port_sensor_battery
      - sensor.master_bedroom_sensor_battery
      - sensor.dylan_bedroom_sensor_battery
      - sensor.tiffany_bedroom_sensor_battery
      - sensor.top_of_stairs_sensor_battery
      - sensor.family_bathroom_sensor_battery
  - name: 'Camera Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {r-ange}%'
    icon: 'mdi:cctv'
    entities:
      - sensor.aarlo_battery_level_back_garden_camera
      - sensor.aarlo_battery_level_carport_camera
  - name: 'Netatmo Sensors (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:weather-cloudy'
    entities:
      - sensor.netatmo_home_rain_battery_percent
      - sensor.netatmo_home_wind_battery_percent
      - sensor.netatmo_netatmo_v3_outdoor_battery_percent
  - name: 'Hue Dimmers (min: {min}%, count: {count})'
    secondary_info: 'Battery levels {range}%'
    icon: 'mdi:light-switch'
    entities:
      - sensor.cheryl_dimmer_battery
      - sensor.dylan_dimmer_battery
      - sensor.tiffany_dimmer_battery
      - sensor.james_dimmer_battery
      - sensor.lounge_dimmer_battery
```

**Screenshots**

<img width="529" alt="Screenshot 2020-06-17 at 15 29 16" src="https://user-images.githubusercontent.com/14061617/84910946-6e07ed00-b0af-11ea-9ff6-0e430acb25a6.png">

**Version**
Card version - 1.4.0
HA version - 0.111.3
