### ISSUE TITLE
No card type configured.

### ISSUE THREAD

**Issue by ggocsei** [maxwroc/battery-state-card#91]
**Describe what is wrong**
On Lovelace Card I got 'No card type configured.'

**YAML configuration**
```yaml

- type: 'custom:battery-state-card'
  title: Custom color thresholds
  thresholds:
    - value: 35
      color: '#8fffe1'
  entities:
    - entity: sensor.bathroom_motion_battery_level
      name: Bathroom motion sensor
```
**Screenshot**
https://pasteboard.co/JeyPXdt.png
https://pasteboard.co/JeyQaRE.png

**Version**
1.4.0

**Comment by maxwroc** [comment]
When you use the UI editor you should not use dash and indent. Please try to below code:
```yaml
type: 'custom:battery-state-card'
title: Custom color thresholds
thresholds:
  - value: 35
    color: '#8fffe1'
entities:
  - entity: sensor.bathroom_motion_battery_level
    name: Bathroom motion sensor
```
